(function(){
'use strict';var wmb=function(a,b){a-=$APP.B(b);return $APP.Ge.A($APP.p,$APP.Mk.o($APP.Zi.j(0>a?0:a," ")),b)},SF=function SF(a){switch(arguments.length){case 2:return SF.j(arguments[0],arguments[1]);case 1:return SF.o(arguments[0]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};
SF.j=function(a,b){if($APP.t(b)){var c=$APP.Mg.j(function(u){return $APP.Ge.A($APP.oj,$APP.p.o(u).length,$APP.Mg.j(function(v){return $APP.p.o($APP.E.j(v,u)).length},b))},a),d=$APP.Mg.j(function(u){return $APP.Ge.j($APP.p,$APP.Zi.j(u,"-"))},c),e=function(u,v,y,A){return[$APP.p.o(u),$APP.p.o($APP.Ge.j($APP.p,$APP.ui.j(v,function(){return function K(H){return new $APP.je(null,function(){for(;;){var V=$APP.t(H);if(V){if($APP.jd(V)){var Y=$APP.dc(V),Z=$APP.B(Y),aa=$APP.ke(Z);a:{for(var da=0;;)if(da<Z){var oa=
$APP.Vc(Y,da),ka=$APP.F.A(oa,0,null);oa=$APP.F.A(oa,1,null);$APP.oe(aa,wmb(oa,$APP.p.o(ka)));da+=1}else{Y=!0;break a}Y=void 0}return Y?$APP.ne($APP.pe(aa),K($APP.ec(V))):$APP.ne($APP.pe(aa),null)}Y=$APP.w(V);aa=$APP.F.A(Y,0,null);Y=$APP.F.A(Y,1,null);return $APP.ae(wmb(Y,$APP.p.o(aa)),K($APP.wc(V)))}return null}},null,null)}($APP.Mg.A($APP.Oq,$APP.Mg.j(function(H){return $APP.E.j(A,H)},a),c))}()))),$APP.p.o(y)].join("")};$APP.js();$APP.js.B($APP.z([e("| "," | "," |",$APP.ug(a,a))]));$APP.js.B($APP.z([e("|-",
"-+-","-|",$APP.ug(a,d))]));d=$APP.t(b);for(var f=null,k=0,m=0;;)if(m<k){var q=f.ma(null,m);$APP.js.B($APP.z([e("| "," | "," |",q)]));m+=1}else if(d=$APP.t(d))f=d,$APP.jd(f)?(d=$APP.dc(f),k=$APP.ec(f),f=d,q=$APP.B(d),d=k,k=q):(q=$APP.w(f),$APP.js.B($APP.z([e("| "," | "," |",q)])),d=$APP.x(f),f=null,k=0),m=0;else return null}else return null};SF.o=function(a){return SF.j($APP.hg($APP.w(a)),a)};SF.K=2;
var xmb=new $APP.r("sci.configs.cljs.pprint","pprint","sci.configs.cljs.pprint/pprint",519877225,null),ymb=new $APP.r("cljs.pprint","*print-pprint-dispatch*","cljs.pprint/*print-pprint-dispatch*",-1820734013,null),zmb=new $APP.r(null,"with-pprint-dispatch","with-pprint-dispatch",-1302026849,null),Amb=new $APP.r("sci.configs.cljs.pprint","with-pprint-dispatch","sci.configs.cljs.pprint/with-pprint-dispatch",1581175222,null),Bmb=new $APP.r("cljs.pprint","code-dispatch","cljs.pprint/code-dispatch",-423875137,
null),Cmb=new $APP.r(null,"print-table","print-table",-2093158225,null),Dmb=new $APP.r("sci.configs.cljs.pprint","cl-format","sci.configs.cljs.pprint/cl-format",1800952185,null),Emb=new $APP.r(null,"code-dispatch","code-dispatch",-511363514,null),Fmb=new $APP.r(null,"*print-pprint-dispatch*","*print-pprint-dispatch*",-1709114492,null),Gmb=new $APP.r("sci.configs.cljs.pprint","print-table","sci.configs.cljs.pprint/print-table",802569398,null),Hmb=new $APP.r(null,"sci.configs.cljs.pprint","sci.configs.cljs.pprint",
-937417453,null),Imb=new $APP.r(null,"pprint","pprint",-1434237374,null),Jmb=new $APP.r(null,"cl-format","cl-format",-1229847214,null);var Kmb=$APP.Wm($APP.MUa),TF=function TF(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return TF.B(arguments[0],arguments[1],arguments[2],c)};TF.B=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.pBa,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,ymb,null,1,null),new $APP.I(null,c,null,1,null))))),null,1,null),$APP.z([d]))))};TF.K=3;
TF.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};var Lmb=$APP.Tm(Fmb,$APP.Yo,new $APP.h(null,1,[$APP.Ck,Kmb],null)),UF=function UF(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.rc(c.slice(0),0,null):null;return UF.B(c)};
UF.B=function(a){var b=$APP.ab,c=$APP.$a,d=$APP.Yo,e=$APP.Cb($APP.rA),f=$APP.Cb($APP.yA),k=$APP.Cb(Lmb);$APP.ab=e;$APP.$a=f;$APP.Yo=k;try{return $APP.Ge.j($APP.$A,a)}finally{$APP.Yo=d,$APP.$a=c,$APP.ab=b}};UF.K=0;UF.P=function(a){return this.B($APP.t(a))};var VF=function VF(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.rc(c.slice(0),0,null):null;return VF.B(c)};
VF.B=function(a){var b=$APP.ab,c=$APP.$a,d=$APP.Cb($APP.rA),e=$APP.Cb($APP.yA);$APP.ab=d;$APP.$a=e;try{return $APP.Ge.j(SF,a)}finally{$APP.$a=c,$APP.ab=b}};VF.K=0;VF.P=function(a){return this.B($APP.t(a))};var WF=function WF(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.rc(c.slice(0),0,null):null;return WF.B(c)};
WF.B=function(a){var b=$APP.ab,c=$APP.$a,d=$APP.Cb($APP.rA),e=$APP.Cb($APP.yA);$APP.ab=d;$APP.$a=e;try{return $APP.Ge.j($APP.zp,a)}finally{$APP.$a=c,$APP.ab=b}};WF.K=0;WF.P=function(a){return this.B($APP.t(a))};
var Mmb=new $APP.h(null,6,[Imb,function(){var a=new $APP.qc(function(){return UF},xmb,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[Hmb,Imb,"sci/configs/cljs/pprint.cljs",13,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,0,$APP.Wv,0,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,16,16,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.st],null)),null,$APP.n(UF)?
UF.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Kmb,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),Fmb,Lmb,Cmb,function(){var a=new $APP.qc(function(){return VF},Gmb,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[Hmb,Cmb,"sci/configs/cljs/pprint.cljs",
18,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,0,$APP.Wv,0,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,22,22,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.st],null)),null,$APP.n(VF)?VF.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Kmb,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=
$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),Jmb,function(){var a=new $APP.qc(function(){return WF},Dmb,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[Hmb,Jmb,"sci/configs/cljs/pprint.cljs",16,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,0,$APP.Wv,0,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,27,27,$APP.Q(new $APP.N(null,
2,5,$APP.O,[$APP.vh,$APP.st],null)),null,$APP.n(WF)?WF.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Kmb,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),Emb,function(){var a=new $APP.qc(function(){return $APP.cB},Bmb,$APP.$f([$APP.rt,$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,
$APP.S,$APP.Nh],["1.2",$APP.MUa,Emb,"cljs/pprint.cljs",16,1,3203,3204,$APP.vc,"The pretty print dispatch function for pretty printing Clojure code.",$APP.n($APP.cB)?$APP.cB.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Kmb,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),zmb,function(){var a=
new $APP.qc(function(){return TF},Amb,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[Hmb,zmb,!0,"sci/configs/cljs/pprint.cljs",39,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Lu,$APP.Lu,$APP.qx,$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Lu,$APP.Lu,$APP.qx,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,7,7,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Lu,$APP.Lu,$APP.qx,
$APP.vh,$APP.Qw],null)),"Execute body with the pretty print dispatch function bound to function.",$APP.n(TF)?TF.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Kmb,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}()],null);$APP.bn(new $APP.h(null,1,[$APP.Wk,new $APP.h(null,1,[$APP.MUa,Mmb],null)],null));
}).call(this);