(function(){
'use strict';var WNd,YNd,ZNd,$Nd,aOd,XNd,bOd,cOd,eOd,C7,fOd,gOd,hOd,jOd,kOd,mOd,D7,nOd,pOd,rOd,tOd,uOd,vOd,wOd,xOd,yOd,zOd,AOd,BOd,DOd,EOd,GOd,F7,HOd,IOd,JOd,KOd,LOd,MOd,NOd,sOd,POd,QOd,ROd,SOd,TOd,UOd,VOd,WOd,XOd,YOd,ZOd,$Od,aPd,bPd,dPd,ePd,fPd,gPd,hPd,iPd,jPd,kPd,lPd,nPd,oPd,pPd,qPd,rPd,sPd,tPd,uPd,vPd,wPd,xPd,yPd,zPd,APd,BPd,CPd,DPd,EPd,FPd,GPd,HPd,JPd,KPd,LPd,MPd,NPd,OPd,PPd,QPd,RPd,SPd,TPd,UPd,VPd,H7,WPd,XPd,YPd,I7,ZPd,$Pd,aQd,bQd,cQd,dQd,eQd,fQd,gQd,hQd,iQd,jQd,kQd,lQd,mQd;
WNd=function(a,b){a:{const c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}b>=0&&$APP.xaa(a,b)};YNd=function(a,b){var c=XNd||$APP.Ma;let d=0,e=a.length,f;for(;d<e;){const k=d+(e-d>>>1);let m;m=c(b,a[k]);m>0?d=k+1:(e=k,f=!m)}c=f?d:-d-1;c<0&&$APP.Aaa(a,-(c+1),0,b)};
ZNd=function(a,b,c){if(a!=null&&a.oi!=null)a.oi(a,b,c);else{var d=ZNd[$APP.ha(a==null?null:a)];if(d!=null)d.A?d.A(a,b,c):d.call(null,a,b,c);else if(d=ZNd._,d!=null)d.A?d.A(a,b,c):d.call(null,a,b,c);else throw $APP.kb("IWatchable.-notify-watches",a);}};$Nd=function(a){for(;;){var b=a.shift();if($APP.n(b)){var c=b.prev;var d=b.Qm;d=$APP.n(d)?d.M?d.M():d.call(null):b.state;if($APP.kg.j(d,c))for(b.prev=d,ZNd(b,c,d),b=b.Jm,c=b.length,d=0;;)if(d<c)YNd(a,b[d]),d+=1;else break}else return null}};
aOd=function(a){return $APP.n($APP.A7.o?$APP.A7.o(a):$APP.A7.call(null,a))?$APP.Cb(a):a};XNd=function(a,b){a=a.sl;b=b.sl;return $APP.G.j(a,b)?0:a-b};bOd=function(a,b){try{return $APP.F.j(a,b)}catch(c){if(c instanceof Error)return null;throw c;}};cOd=function(a){$APP.n(B7)?YNd(B7,a):$Nd([a]);return a};
eOd=function(a,b,c,d){if($APP.n(b)){a.constant=!0;c.push(b);a.sources=c;b=a.sources.length;for(c=0;;)if(c<b){var e=a.sources[c];if($APP.n($APP.A7.o?$APP.A7.o(e):$APP.A7.call(null,e))&&($APP.n(function(){var m=a.constant;return $APP.n(m)?$APP.db(e.constant):m}())&&(a.constant=!1),e.Jm.push(a),e.sl>a.sl))for(var f=[e];;){var k=f.shift();if($APP.n(k))k.sl=$APP.$g.j(dOd,$APP.Fc),f=f.concat(k.Jm);else break}c+=1}else break;a.Qm=function(){for(var m=a.sources.slice(),q=aOd(m.pop()),u=m.length,v=0;;)if(v<
u)m[v]=aOd(m[v]),v+=1;else break;return a.state=q.apply(null,m)};a.update=d}return cOd(a)};C7=function(a,b,c,d,e,f,k,m,q,u,v){this.meta=a;this.state=b;this.sl=c;this.prev=d;this.sources=e;this.Jm=f;this.Qm=k;this.watches=m;this.update=q;this.constant=u;this.qk=v;this.V=2147909632;this.Y=98306};$APP.A7=function(a){return a instanceof C7?a:null};fOd=function(a){var b=$APP.A7(a);return $APP.n($APP.n(b)?a.Qm:b)?a:null};gOd=function(a){var b=$APP.A7(a);return $APP.n($APP.n(b)?a.update:b)?a:null};
hOd=function(a){var b=$APP.A7(a);return $APP.n($APP.n(b)?$APP.db(fOd(a)):b)?a:null};jOd=function(a){var b=$APP.Mg,c=b.j,d=$APP.Im.j,e=$APP.Cb(iOd);a=e.o?e.o(a):e.call(null,a);return c.call(b,$APP.w,d.call($APP.Im,2,a))};kOd=function(a){var b=new $APP.N(null,2,5,$APP.O,[a,null],null);a=$APP.rg(jOd(b));b=$APP.rg(jOd(b));return $APP.t($APP.eq.j(a,b))};mOd=function(a,b){return $APP.oA($APP.si.j(lOd,a),b)};D7=function(a){return $APP.Mf.j($APP.vc,$APP.Yd(a))};
nOd=function(a){return $APP.Sh("formula expansion contains unsupported %s form","%s",a)};pOd=function(a,b){a=$APP.w(a);return $APP.db(oOd.call(null,a))&&$APP.db(b.o?b.o(a):b.call(null,a))&&$APP.wd(new $APP.ng(null,new $APP.h(null,4,[$APP.fga,"null",$APP.Eh,"null",$APP.iga,"null",$APP.Mh,"null"],null),null),a)};
rOd=function(a,b){b=b.o?b.o(a):b.call(null,a);b=$APP.n(b)?b:$APP.wd(new $APP.ng(null,new $APP.h(null,3,["js",null,"clojure.core",null,"cljs.core",null],null),null),$APP.de(a));return(b=$APP.db(b))?(b=oOd.call(null,a),$APP.n(b)?b:!$APP.wd(qOd,a)):b};
tOd=function(a,b){if($APP.db(rOd(a,b)))return a;b=function(){var c=$APP.Cb(E7);return c.o?c.o(a):c.call(null,a)}();$APP.n(b)||$APP.$g.A(E7,$APP.Xd,$APP.C(a,new $APP.h(null,1,[sOd,$APP.sj.M()],null)));return sOd.o($APP.Yc(function(){var c=$APP.Cb(E7);return c.o?c.o(a):c.call(null,a)}()))};uOd=function(a,b){return $APP.Mf.j($APP.Uc(a),$APP.Mg.j(function(c){return $APP.Jk.j(function(d){return F7.j?F7.j(d,b):F7.call(null,d,b)},c)},a))};
vOd=function(a,b){return $APP.Mf.j($APP.Uc(a),$APP.Mg.j(function(c){return F7.j?F7.j(c,b):F7.call(null,c,b)},a))};
wOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);var e=$APP.Zg.o(b);b=$APP.$e.B(function(f){var k=$APP.F.A(f,0,null),m=$APP.F.A(f,1,null);f=$APP.O;var q=$APP.Cb(e);m=F7.j?F7.j(m,q):F7.call(null,m,q);f=new $APP.N(null,2,5,f,[k,m],null);$APP.$g.A(e,$APP.Xd,k);return f},$APP.z([$APP.Im.j(2,c)]));return D7($APP.al.o($APP.t($APP.R.B(new $APP.I(null,a,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(b)))),null,1,null),$APP.z([$APP.Mg.j(function(f){var k=
$APP.Cb(e);return F7.j?F7.j(f,k):F7.call(null,f,k)},d)])))))};xOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);var e=$APP.w(d);d=$APP.x(d);return D7($APP.al.o($APP.t($APP.R.B(new $APP.I(null,a,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,e,null,1,null),$APP.Mg.j(function(f){var k=$APP.Xd.j(b,e);return F7.j?F7.j(f,k):F7.call(null,f,k)},d)])))))};
yOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);c=$APP.x(c);return D7($APP.al.o($APP.t($APP.R.j(new $APP.I(null,a,null,1,null),$APP.Mg.j(function(d){return F7.j?F7.j(d,b):F7.call(null,d,b)},c)))))};zOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);c=$APP.x(c);return D7($APP.al.o($APP.t($APP.R.j(new $APP.I(null,a,null,1,null),$APP.Mg.j(function(d){var e=$APP.od(d)?$APP.G.j($APP.kga,$APP.w(d))?xOd:$APP.G.j($APP.yh,$APP.w(d))?yOd:F7:F7;return e.j?e.j(d,b):e.call(null,d,b)},c)))))};
AOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);var e=$APP.Dd.A($APP.Xd,b,$APP.Mg.j($APP.w,$APP.Im.j(2,c)));b=$APP.Mg.A(function(f,k){return f.o?f.o(k):f.call(null,k)},$APP.Ue(new $APP.N(null,2,5,$APP.O,[$APP.Hd,function(f){return F7.j?F7.j(f,e):F7.call(null,f,e)}],null)),c);return D7($APP.al.o($APP.t($APP.R.B(new $APP.I(null,a,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(b)))),null,1,null),$APP.z([$APP.Mg.j(function(f){return F7.j?F7.j(f,e):
F7.call(null,f,e)},d)])))))};
BOd=function(a,b){var c=$APP.t(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d)instanceof $APP.r?new $APP.N(null,1,5,$APP.O,[$APP.w(d)],null):null;d=$APP.n(c)?$APP.wc(d):d;d=$APP.id($APP.w(d))?new $APP.N(null,1,5,$APP.O,[d],null):d;var e=$APP.n(c)?$APP.Xd.j(b,$APP.w(c)):b;b=$APP.Mg.j(function(f){var k=$APP.t(f);f=$APP.w(k);k=$APP.x(k);var m=$APP.Mf.j(e,$APP.bm.j(function(q){return $APP.G.j($APP.vh,q)},f));return D7($APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(f)))),null,1,
null),$APP.Mg.j(function(q){return F7.j?F7.j(q,m):F7.call(null,q,m)},k)))))},d);return D7($APP.al.o($APP.t($APP.R.B(new $APP.I(null,a,null,1,null),c,$APP.z([b])))))};DOd=function(a){var b=$APP.sj.M();$APP.$g.F(COd,$APP.lg,b,a);return b};
EOd=function(a,b){function c(k){return new $APP.I(null,$APP.w(k),new $APP.I(null,$APP.Mg.j(function(m){return F7.j?F7.j(m,b):F7.call(null,m,b)},$APP.wc(k)),null,1,null),2,null)}var d=$APP.t(a);a=$APP.w(d);d=$APP.x(d);var e=$APP.w(d),f=$APP.x(d);d=$APP.w(f);f=$APP.x(f);e=F7.j?F7.j(e,b):F7.call(null,e,b);f=$APP.Mg.j(function(k){return F7.j?F7.j(k,b):F7.call(null,k,b)},f);return D7($APP.al.o($APP.t($APP.R.B(new $APP.I(null,a,null,1,null),new $APP.I(null,e,null,1,null),$APP.z([$APP.od(d)?new $APP.N(null,
1,5,$APP.O,[c(d)],null):$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,d,null,1,null),f))))])))))};
GOd=function(a,b){if($APP.G.j(0,$APP.B(a)))return a;if($APP.G.j($APP.Jh,$APP.w(a)))return EOd(a,b);if($APP.G.j($APP.xh,$APP.w(a)))return zOd(a,b);if($APP.wd(new $APP.ng(null,new $APP.h(null,2,[$APP.Ah,"null",$APP.Fh,"null"],null),null),$APP.w(a)))return wOd(a,b);if($APP.G.j($APP.hga,$APP.w(a)))return AOd(a,b);if($APP.G.j($APP.Gh,$APP.w(a)))return BOd(a,b);if($APP.G.j($APP.P,$APP.w(a)))return DOd(a);if($APP.G.j($APP.qj,$APP.w(a)))return DOd($APP.Oc(a));if($APP.G.j($APP.rj,$APP.w(a)))return DOd(new $APP.I(null,
$APP.ZFa,new $APP.I(null,$APP.Oc(a),null,1,null),2,null));if(pOd(a,b))throw new FOd(nOd($APP.w(a)));return D7($APP.Mg.j(function(c){return F7.j?F7.j(c,b):F7.call(null,c,b)},a))};F7=function(a,b){return a instanceof $APP.r?tOd(a,b):$APP.gd(a)?uOd(a,b):$APP.cd(a)?vOd(a,b):$APP.id(a)?vOd(a,b):$APP.od(a)?GOd(a,b):a};
HOd=function(a,b){var c=oOd,d=E7,e=COd,f=$APP.Zg.o($APP.og),k=$APP.Zg.o($APP.M);oOd=b;E7=f;COd=k;try{var m=F7(mOd(b,a),$APP.og),q=$APP.ad($APP.Cb(COd))?new $APP.N(null,2,5,$APP.O,[$APP.ff,$APP.ff],null):$APP.Ge.A($APP.Mg,$APP.Oq,$APP.Cb(COd)),u=$APP.F.A(q,0,null),v=$APP.F.A(q,1,null),y=$APP.Mf.j(u,$APP.Mg.j(function(D){return sOd.o($APP.Yc(D))},$APP.Cb(E7))),A=$APP.Mf.j(v,$APP.Cb(E7));return new $APP.N(null,2,5,$APP.O,[new $APP.I(null,$APP.wq,new $APP.I(null,y,new $APP.I(null,m,null,1,null),2,null),
3,null),A],null)}finally{COd=e,E7=d,oOd=c}};IOd=new $APP.r("cljs.core","IReset","cljs.core/IReset",-1478584309,null);JOd=new $APP.r(null,"cell\x3d","cell\x3d",1747247109,null);KOd=new $APP.r(null,"cell?","cell?",-1714515962,null);LOd=new $APP.r(null,"defc\x3d","defc\x3d",561895827,null);MOd=new $APP.r(null,"cell-doseq","cell-doseq",1972399407,null);NOd=new $APP.r("sci.configs.hoplon.javelin","dosync*","sci.configs.hoplon.javelin/dosync*",960816078,null);
$APP.G7=new $APP.r("javelin.core","formula","javelin.core/formula",360759737,null);sOd=new $APP.J("sci.configs.hoplon.javelin","h","sci.configs.hoplon.javelin/h",1590953761);$APP.OOd=new $APP.r("javelin.core","with-let","javelin.core/with-let",-1430245746,null);POd=new $APP.r(null,"constant","constant",1260922224,null);QOd=new $APP.r(null,"constant?","constant?",1756965709,null);ROd=new $APP.r(null,"item__111642__auto__","item__111642__auto__",348435782,null);
SOd=new $APP.r("javelin.core","set-cell!","javelin.core/set-cell!",-1818735883,null);TOd=new $APP.r("javelin.core","lens","javelin.core/lens",-60197558,null);UOd=new $APP.r("sci.configs.hoplon.javelin","dosync","sci.configs.hoplon.javelin/dosync",-1963203662,null);VOd=new $APP.r(null,"destroy-cell!","destroy-cell!",-1668103066,null);WOd=new $APP.r("sci.configs.hoplon.javelin","defc\x3d","sci.configs.hoplon.javelin/defc\x3d",-2085754688,null);
XOd=new $APP.r("sci.configs.hoplon.javelin","cell\x3d","sci.configs.hoplon.javelin/cell\x3d",-1881869996,null);YOd=new $APP.r(null,"c__111458__auto__","c__111458__auto__",-1913306107,null);ZOd=new $APP.r("sci.configs.hoplon.javelin","cell-let-1","sci.configs.hoplon.javelin/cell-let-1",-1419030109,null);$Od=new $APP.r(null,"cell-let","cell-let",1760937693,null);aPd=new $APP.r(null,"keep-watches?","keep-watches?",1434000213,null);bPd=new $APP.r(null,"cell","cell",-1890190685,null);
$APP.cPd=new $APP.r("javelin.core","cell-let","javelin.core/cell-let",1906090463,null);dPd=new $APP.r(null,"formula-of","formula-of",125010619,null);ePd=new $APP.r(null,"cell-let-1","cell-let-1",238772466,null);fPd=new $APP.r(null,"cell-map","cell-map",-519069699,null);gPd=new $APP.r("javelin.core","cell-map","javelin.core/cell-map",-295619841,null);hPd=new $APP.r(null,"rank","rank",-66196975,null);iPd=new $APP.r(null,"numwatches","numwatches",2058987374,null);
jPd=new $APP.r(null,"resource","resource",1892430363,null);kPd=new $APP.r("javelin.core","-\x3eCell","javelin.core/-\x3eCell",-1899359988,null);lPd=new $APP.r("javelin.core","cell?","javelin.core/cell?",-1563069696,null);$APP.mPd=new $APP.r("javelin.core","cell\x3d","javelin.core/cell\x3d",1664959239,null);nPd=new $APP.r(null,"dosync*","dosync*",-1636503363,null);oPd=new $APP.r("cljs.core","for","cljs.core/for",-89947499,null);
pPd=new $APP.r("sci.configs.hoplon.javelin","formulet","sci.configs.hoplon.javelin/formulet",250074878,null);qPd=new $APP.r(null,"Cell","Cell",1694176314,null);rPd=new $APP.r(null,"deps","deps",-771075450,null);sPd=new $APP.r("javelin.core","set-cell!\x3d","javelin.core/set-cell!\x3d",-2127309625,null);tPd=new $APP.r("javelin.core","lift","javelin.core/lift",-1655883756,null);uPd=new $APP.r(null,"formula?","formula?",-1583432172,null);
vPd=new $APP.r("sci.configs.hoplon.javelin","formula-of","sci.configs.hoplon.javelin/formula-of",-364661814,null);wPd=new $APP.r("sci.configs.hoplon.javelin","with-let","sci.configs.hoplon.javelin/with-let",517558481,null);xPd=new $APP.r("javelin.core","input?","javelin.core/input?",-306170452,null);yPd=new $APP.r("sci.configs.hoplon.javelin","cell-doseq","sci.configs.hoplon.javelin/cell-doseq",373333598,null);zPd=new $APP.r("cljs.core","ISwap","cljs.core/ISwap",-190928468,null);
APd=new $APP.J("javelin.core","none","javelin.core/none",1150337088);BPd=new $APP.r(null,"formulet","formulet",-216554065,null);CPd=new $APP.r(null,".-update",".-update",1268289682,null);DPd=new $APP.r("javelin.core","destroy-cell!","javelin.core/destroy-cell!",-1752668316,null);EPd=new $APP.r("cljs.core","IWatchable","cljs.core/IWatchable",-1531379261,null);FPd=new $APP.r("javelin.core","constant?","javelin.core/constant?",1369475151,null);
GPd=new $APP.r("javelin.core","dosync*","javelin.core/dosync*",-1788629569,null);HPd=new $APP.r(null,"alts!","alts!",104119866,null);$APP.IPd=new $APP.r("js","setInterval","js/setInterval",2090002939,null);JPd=new $APP.r(null,"cell-doseq*","cell-doseq*",1917821935,null);KPd=new $APP.r("sci.configs.hoplon.javelin","set-cell!\x3d","sci.configs.hoplon.javelin/set-cell!\x3d",1859815190,null);LPd=new $APP.r(null,"formula","formula",580806335,null);MPd=new $APP.r(null,"foo","foo",-1385541733,null);
NPd=new $APP.r("sci.configs.hoplon.javelin","cell-let","sci.configs.hoplon.javelin/cell-let",-2054817940,null);OPd=new $APP.r(null,"defc","defc",-1111689649,null);PPd=new $APP.r("javelin.core","cell","javelin.core/cell",-1773511263,null);QPd=new $APP.r(null,"-\x3eCell","-\x3eCell",-1209682942,null);RPd=new $APP.r("javelin.core","cell-let-1","javelin.core/cell-let-1",386008048,null);SPd=new $APP.r("javelin.core","formula?","javelin.core/formula?",-1199220470,null);
TPd=new $APP.r("javelin.core","Cell","javelin.core/Cell",2144368952,null);UPd=new $APP.r(null,"lift","lift",-1750803734,null);VPd=new $APP.r(null,"set-formula!","set-formula!",548458029,null);H7=new $APP.r(null,"updatefn","updatefn",-2058610680,null);WPd=new $APP.r(null,"dosync","dosync",336328035,null);XPd=new $APP.r(null,"set-cell!","set-cell!",-1938905101,null);YPd=new $APP.r(null,"input?","input?",-152311646,null);
I7=new $APP.r(null,"sci.configs.hoplon.javelin","sci.configs.hoplon.javelin",2099549778,null);ZPd=new $APP.r(null,"sinks","sinks",-1243609492,null);$Pd=new $APP.r("javelin.core","set-formula!","javelin.core/set-formula!",965634351,null);aQd=new $APP.r("javelin.core","deref*","javelin.core/deref*",1447291123,null);bQd=new $APP.r(null,"bar","bar",254284943,null);cQd=new $APP.r(null,"set-cell!\x3d","set-cell!\x3d",-2012575291,null);dQd=new $APP.r(null,"thunk","thunk",74255732,null);
eQd=new $APP.r("sci.configs.hoplon.javelin","defc","sci.configs.hoplon.javelin/defc",1533855632,null);fQd=new $APP.r(null,"lens","lens",-984575916,null);gQd=new $APP.r(null,"item__111639__auto__","item__111639__auto__",242104860,null);hQd=new $APP.r(null,"deref*","deref*",548228593,null);iQd=new $APP.r(null,"javelin.core","javelin.core",1164167622,null);jQd=new $APP.r("javelin.core","alts!","javelin.core/alts!",219028260,null);kQd=new $APP.r(null,"lens?","lens?",1968859788,null);
lQd=new $APP.r("javelin.core","lens?","javelin.core/lens?",-1975449714,null);mQd=new $APP.r("javelin.core","cell-doseq*","javelin.core/cell-doseq*",2107983085,null);var B7=null,dOd=$APP.Zg.o(0),J7=function J7(a){switch(arguments.length){case 1:return J7.o(arguments[0]);case 2:return J7.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};J7.o=function(a){return J7.j(a,null)};
J7.j=function(a,b){var c=a.sources;a.sources=[];a.update=null;a.Qm=null;$APP.n(b)||(a.watches=$APP.M,a.qk=0);b=c.length;for(var d=0;;)if(d<b){var e=function(){var k=c[d];return $APP.A7.o?$APP.A7.o(k):$APP.A7.call(null,k)}();if($APP.n(e)){var f=e;WNd(f.Jm,function(){return function(k){return $APP.G.j(k,a)}}(d,f,e,b,c))}d+=1}else return null};J7.K=2;
var K7=function K7(a){switch(arguments.length){case 1:return K7.o(arguments[0]);case 2:return K7.j(arguments[0],arguments[1]);case 3:return K7.A(arguments[0],arguments[1],arguments[2]);case 4:return K7.F(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};K7.o=function(a){J7.j(a,!0);return eOd(a,null,null,null)};K7.j=function(a,b){J7.j(a,!0);return eOd(a,b,[],null)};
K7.A=function(a,b,c){J7.j(a,!0);return eOd(a,b,$APP.Kl.o(c),null)};K7.F=function(a,b,c,d){J7.j(a,!0);return eOd(a,b,$APP.Kl.o(c),d)};K7.K=4;$APP.g=C7.prototype;$APP.g.la=function(a,b){return $APP.Jg(b,$APP.z(["#object [javelin.core.Cell ",$APP.Yg.B($APP.z([this.state])),"]"]))};$APP.g.ka=function(a,b){return new C7(b,this.state,this.sl,this.prev,this.sources,this.Jm,this.Qm,this.watches,this.update,this.constant,this.qk)};$APP.g.ja=function(){return this.meta};$APP.g.Oa=function(){return this.state};
$APP.g.le=function(a,b){if($APP.n(gOd.o?gOd.o(this):gOd.call(null,this)))a=this.update,a.o?a.o(b):a.call(null,b);else if($APP.n(hOd.o?hOd.o(this):hOd.call(null,this)))this.state=b,cOd(this);else throw Error("can't swap! or reset! formula cell");return this.state};$APP.g.Wk=function(a,b){a=this.state;b=b.o?b.o(a):b.call(null,a);return $APP.Le(this,b)};$APP.g.Xk=function(a,b,c){a=this.state;b=b.j?b.j(a,c):b.call(null,a,c);return $APP.Le(this,b)};
$APP.g.Yk=function(a,b,c,d){a=this.state;b=b.A?b.A(a,c,d):b.call(null,a,c,d);return $APP.Le(this,b)};$APP.g.Zk=function(a,b,c,d,e){return $APP.Le(this,$APP.Ge.ba(b,this.state,c,d,e))};
$APP.g.oi=function(a,b,c){if(0<this.qk){a=$APP.t(this.watches);for(var d=null,e=0,f=0;;)if(f<e){var k=d.ma(null,f),m=$APP.F.A(k,0,null);k=$APP.F.A(k,1,null);k.F?k.F(m,this,b,c):k.call(null,m,this,b,c);f+=1}else if(a=$APP.t(a))$APP.jd(a)?(d=$APP.dc(a),a=$APP.ec(a),m=d,e=$APP.B(d),d=m):(d=$APP.w(a),m=$APP.F.A(d,0,null),k=$APP.F.A(d,1,null),k.F?k.F(m,this,b,c):k.call(null,m,this,b,c),a=$APP.x(a),d=null,e=0),f=0;else return null}else return null};
$APP.g.Cj=function(a,b,c){$APP.wd(this.watches,b)||(this.qk+=1);return this.watches=$APP.lg.A(this.watches,b,c)};$APP.g.Dj=function(a,b){return $APP.wd(this.watches,b)?(--this.qk,this.watches=$APP.ri.j(this.watches,b)):null};$APP.L7=function L7(a){switch(arguments.length){case 1:return L7.o(arguments[0]);case 2:return L7.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};$APP.L7.o=function(a){return $APP.L7.j(a,null)};
$APP.L7.j=function(a,b){return function(){return eOd($APP.M7.o?$APP.M7.o(APd):$APP.M7.call(null,APd),a,Array.prototype.slice.call(arguments),b)}};$APP.L7.K=2;$APP.M7=function M7(a){switch(arguments.length){case 1:return M7.o(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return M7.B(arguments[0],c)}};
$APP.M7.o=function(a){return new C7(null,a,$APP.$g.j(dOd,$APP.Fc),a,[],[],null,$APP.M,null,!1,0)};$APP.M7.B=function(a,b){b=$APP.ve(b);b=$APP.E.j(b,$APP.l);return new C7(b,a,$APP.$g.j(dOd,$APP.Fc),a,[],[],null,$APP.M,null,!1,0)};$APP.M7.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};$APP.M7.K=1;var nQd=function nQd(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.rc(c.slice(0),0,null):null;return nQd.B(c)};
nQd.B=function(a){function b(d,e){return new $APP.N(null,2,5,$APP.O,[$APP.kg.j(d,e),e],null)}var c=$APP.Zg.o($APP.Zi.j($APP.B(a),APd));return $APP.Ge.j($APP.L7.o(function(){function d(f){var k=null;if(arguments.length>0){k=0;for(var m=Array(arguments.length-0);k<m.length;)m[k]=arguments[k+0],++k;k=new $APP.rc(m,0,null)}return e.call(this,k)}function e(f){var k=$APP.Cb(c);k=$APP.Zr.o($APP.Mg.j($APP.Oc,$APP.cf.j($APP.w,$APP.Mg.A(b,k,f))));$APP.Le(c,f);return k}d.K=0;d.P=function(f){f=$APP.t(f);return e(f)};
d.B=e;return d}()),a)};nQd.K=0;nQd.P=function(a){return this.B($APP.t(a))};var FOd=Error,N7=$APP.Wm(iQd),iOd=new $APP.Tg(function(){return $APP.Vm($APP.mk(),"destructure")},null),oQd=new $APP.Tg(function(){return $APP.Vm($APP.mk(),"macroexpand-1")},null),lOd=function lOd(a,b){if($APP.od(b)){var d=$APP.Cb(oQd);d=d.o?d.o(b):d.call(null,b);return d===b?b:lOd.j?lOd.j(a,d):lOd.call(null,a,d)}return b},oOd=null,E7=null,COd=null,qOd=new $APP.ng(null,new $APP.h(null,22,[$APP.vh,"null",$APP.wh,"null",$APP.fga,"null",$APP.xh,"null",$APP.gga,"null",$APP.Ah,"null",$APP.Bh,"null",$APP.hga,
"null",$APP.Ch,"null",$APP.Dh,"null",$APP.Eh,"null",$APP.iga,"null",$APP.Fh,"null",$APP.jga,"null",$APP.Gh,"null",$APP.Hh,"null",$APP.Ih,"null",$APP.Jh,"null",$APP.Kh,"null",$APP.P,"null",$APP.Lh,"null",$APP.Mh,"null"],null),null),O7=function O7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return O7.B(arguments[0],arguments[1],arguments[2],c)};
O7.B=function(a,b,c,d){a=$APP.F.A(c,0,null);c=$APP.F.A(c,1,null);return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,a,null,1,null),new $APP.I(null,c,null,1,null))))),null,1,null),$APP.z([d,new $APP.I(null,a,null,1,null)]))))};O7.K=3;O7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};
var P7=function P7(a){switch(arguments.length){case 3:return P7.A(arguments[0],arguments[1],arguments[2]);case 4:return P7.F(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};P7.A=function(a,b,c){b=HOd(c,b);a=$APP.F.A(b,0,null);b=$APP.F.A(b,1,null);return D7($APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,a,null,1,null)))),null,1,null),b))))};
P7.F=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.OOd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,YOd,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.mPd,null,1,null),new $APP.I(null,c,null,1,null)))),null,1,null))))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Ih,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,CPd,null,1,null),new $APP.I(null,YOd,
null,1,null)))),null,1,null),$APP.z([new $APP.I(null,d,null,1,null)])))),null,1,null)]))))};P7.K=4;var Q7=function Q7(a){switch(arguments.length){case 4:return Q7.F(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Q7.ba(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};
Q7.F=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,sPd,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,d,null,1,null),new $APP.I(null,null,null,1,null)]))))};
Q7.ba=function(a,b,c,d,e){b=HOd(d,b);a=$APP.F.A(b,0,null);b=$APP.F.A(b,1,null);return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$Pd,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,a,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(b)))),null,1,null),new $APP.I(null,e,null,1,null)]))))};Q7.K=5;
var R7=function R7(a){switch(arguments.length){case 4:return R7.F(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return R7.ba(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};
R7.F=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Mh,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,PPd,null,1,null),new $APP.I(null,d,null,1,null)))),null,1,null)]))))};
R7.ba=function(a,b,c,d,e){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Mh,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,d,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,PPd,null,1,null),new $APP.I(null,e,null,1,null)))),null,1,null)]))))};R7.K=5;
var S7=function S7(a){switch(arguments.length){case 4:return S7.F(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=4<c.length?new $APP.rc(c.slice(4),0,null):null;return S7.B(arguments[0],arguments[1],arguments[2],arguments[3],c)}};
S7.F=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Mh,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.mPd,null,1,null),new $APP.I(null,d,null,1,null)))),null,1,null)]))))};
S7.B=function(a,b,c,d,e){a=$APP.F.A(e,0,null);b=$APP.F.A(e,1,null);b=(e=typeof d==="string")?b:a;return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Mh,null,1,null),new $APP.I(null,c,null,1,null),$APP.z([e?new $APP.N(null,1,5,$APP.O,[d],null):null,new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.mPd,null,1,null),new $APP.I(null,e?a:d,null,1,null),$APP.z([$APP.n(b)?new $APP.N(null,1,5,$APP.O,[b],null):null])))),null,1,null)]))))};
S7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);var e=$APP.x(d);d=$APP.w(e);e=$APP.x(e);return this.B(b,a,c,d,e)};S7.K=4;var T7=function T7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return T7.B(arguments[0],arguments[1],arguments[2],c)};
T7.B=function(a,b,c,d){return $APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(c)))),null,1,null),$APP.z([d])))),null,1,null)))),null,1,null),c)))};T7.K=3;T7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};
var U7=function U7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return U7.B(arguments[0],arguments[1],arguments[2],c)};
U7.B=function(a,b,c,d){a=$APP.Im.j(2,c);return $APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o($APP.Mg.j($APP.w,a))))),null,1,null),$APP.z([d])))),null,1,null)))),null,1,null),$APP.Mg.j($APP.Oc,a))))};U7.K=3;
U7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};var V7=function V7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return V7.B(arguments[0],arguments[1],arguments[2],c)};
V7.B=function(a,b,c,d){a=$APP.F.A(c,0,null);b=$APP.F.A(c,1,null);c=kOd(a);a=$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(new $APP.I(null,a,null,1,null))))),null,1,null),$APP.z([new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(c)))),null,1,null)])))),null,1,null)))),null,1,null),new $APP.I(null,b,null,1,null))));
return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(c)))),null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,gPd,null,1,null),new $APP.I(null,$APP.Eya,null,1,null),$APP.z([new $APP.I(null,a,null,1,null)])))),null,1,null))))),null,1,null),$APP.z([d]))))};V7.K=3;
V7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};var W7=function W7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return W7.B(arguments[0],arguments[1],arguments[2],c)};
W7.B=function(a,b,c,d){b=$APP.t(c);a=$APP.w(b);c=$APP.x(b);b=$APP.w(c);c=$APP.x(c);return $APP.db($APP.t(c))?$APP.al.o($APP.t($APP.R.B(new $APP.I(null,RPd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,a,null,1,null),new $APP.I(null,b,null,1,null))))),null,1,null),$APP.z([d])))):$APP.al.o($APP.t($APP.R.B(new $APP.I(null,RPd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,a,null,1,null),new $APP.I(null,b,null,1,null))))),null,1,null),$APP.z([new $APP.I(null,
$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.cPd,null,1,null),new $APP.I(null,$APP.Fd(c),null,1,null),$APP.z([d])))),null,1,null)]))))};W7.K=3;W7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};var X7=function X7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=2<c.length?new $APP.rc(c.slice(2),0,null):null;return X7.B(arguments[0],arguments[1],c)};
X7.B=function(a,b,c){return $APP.al.o($APP.t($APP.R.j(new $APP.I(null,NOd,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.M()))),null,1,null),$APP.z([c])))),null,1,null))))};X7.K=2;X7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.B(b,a,c)};
var Y7=function Y7(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return Y7.B(arguments[0],arguments[1],arguments[2],c)};
Y7.B=function(a,b,c,d){if($APP.G.j(2,$APP.B(c)))return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,mQd,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,$APP.ut,null,1,null)))),null,1,null),new $APP.I(null,$APP.Oc(c),null,1,null)))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(new $APP.I(null,gQd,
null,1,null))))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.cPd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.w(c),null,1,null),new $APP.I(null,gQd,null,1,null))))),null,1,null),$APP.z([d])))),null,1,null)])))),null,1,null)]))));c=$APP.Im.j(2,c);a=$APP.$e.B($APP.Oc,$APP.z([$APP.cf.j($APP.Lk.j($APP.si.j($APP.G,$APP.RBa),$APP.w),c)]));b=$APP.yg.j($APP.He($APP.Lk.j($APP.be,$APP.w)),c);var e=$APP.$e.B($APP.Hd,$APP.z([$APP.zg.j($APP.He($APP.Lk.j($APP.be,
$APP.w)),c)]));c=$APP.$e.B($APP.Lk.j(kOd,$APP.w),$APP.z([b]));var f=$APP.Mg.j($APP.Oc,b),k=$APP.Ve.j($APP.B(f),$APP.km.o($APP.sj));b=$APP.R.j($APP.Yi.j($APP.Mg.j($APP.w,b),k),e);return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,mQd,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.G7,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(k)))),null,
1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,oPd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(b)))),null,1,null),$APP.z([new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(c)))),null,1,null)])))),null,1,null)])))),null,1,null)))),null,1,null),f))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(new $APP.I(null,ROd,null,1,null))))),null,1,null),$APP.z([new $APP.I(null,
$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.cPd,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.o(c)))),null,1,null),new $APP.I(null,ROd,null,1,null),$APP.z([a]))))),null,1,null),$APP.z([d])))),null,1,null)])))),null,1,null)]))))};Y7.K=3;Y7.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};
var pQd=$APP.lg.B($APP.Xm($APP.$f([$APP.C(VPd,new $APP.h(null,3,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,$APP.Qu],null),new $APP.N(null,3,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt],null),new $APP.N(null,4,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt,H7],null))),$APP.S,"Given a Cell and optional formula function f and the cells f depends on,\n  sources, updates the formula for this cell in place. If f and/or sources\n  is not spcified they are set to nil.",
$APP.Xy,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,4,$APP.Wv,4,$APP.mz,new $APP.N(null,4,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,$APP.Qu],null),new $APP.N(null,3,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt],null),new $APP.N(null,4,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt,H7],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,$APP.Qu],null),new $APP.N(null,3,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt],null),new $APP.N(null,4,
5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt,H7],null)),$APP.Ox,$APP.Q(null,null,null,null)],null)],null)),$APP.C(fQd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.Qu],null))),$APP.S,"Returns a new lens whose value is the same as c's with update function f.\n  This is equivalent to ((formula identity f) c)."],null)),$APP.C(kQd,new $APP.h(null,1,[$APP.yt,!0],null)),$APP.C(uPd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null))),
$APP.S,"Returns c if c is a formula cell, nil otherwise."],null)),$APP.C(LPd,new $APP.h(null,3,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Qu],null),new $APP.N(null,2,5,$APP.O,[$APP.Qu,H7],null))),$APP.S,"Returns a function that returns a formula cell with f as its formula, and\n  if updatefn is provided the returned cell is a lens.\n\n  See also: the javelin.core/cell\x3d macro.\n\n      (def x (cell 100))\n      (def y (cell 200))\n\n      (def z1 (cell\x3d (+ x y)))\n      (def z2 ((formula +) x y))\n\n  The formula cells z1 and z2 are equivalent.",
$APP.Xy,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.Qu],null),new $APP.N(null,2,5,$APP.O,[$APP.Qu,H7],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Qu],null),new $APP.N(null,2,5,$APP.O,[$APP.Qu,H7],null)),$APP.Ox,$APP.Q(null,null)],null)],null)),$APP.C(qPd,new $APP.h(null,1,[$APP.yt,!0],null)),$APP.C(UPd,new $APP.h(null,1,[$APP.HRa,!0],null)),$APP.C(QOd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,
1,5,$APP.O,[$APP.Pu],null))),$APP.S,"Returns c if c is a constant formula cell, nil otherwise."],null)),$APP.C(HPd,new $APP.h(null,3,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.Hya],null))),$APP.S,"Given a number of cells, returns a formula cell whose value is a seq of\n  values from cells that changed in the last update. Note that multiple cells\n  may update atomically, which is why the formula's value is a seq.\n\n  Consider:\n\n      (def a (cell {:x 1 :y 2}))\n      (def x (cell\x3d (:x a)))\n      (def y (cell\x3d (:y a)))\n      (def z (alts! x y))\n\n  then,\n\n      (deref z) ;\x3d\x3e (1 2)\n\n      (swap! a assoc :x 42)\n      (deref z) ;\x3d\x3e (42)\n\n      (reset! a {:x 10 :y 20})\n      (deref z) ;\x3d\x3e (10 20)\n  ",
$APP.Xy,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,0,$APP.Wv,0,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Hya)],null),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.Hya],null)),$APP.Ox,$APP.Q(null)],null)],null)),$APP.C(fPd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Qu,$APP.Pu],null))),$APP.S,"Given a function f and a cell c that contains a seqable collection of items,\n  returns a seq of formula cells such that the ith formula cell is equivalent\n  to (cell\x3d (f (nth c i)))."],
null)),$APP.C(XPd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.mv],null))),$APP.S,"Converts c to an input cell in place, setting its contents to x. It's okay\n  if c was already an input cell. Changes will be propagated to any cells that\n  depend on c."],null)),$APP.C(bPd,new $APP.h(null,1,[$APP.yt,!0],null)),$APP.C(KOd,new $APP.h(null,1,[$APP.yt,!0],null)),$APP.C(JPd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.Qu],
null))),$APP.S,"Given a function f and a cell c that contains a seqable collection of items,\n  calls f for side effects once for each item in c, passing one argument: a\n  formula cell equivalent to (cell\x3d (nth c i)) for the ith item in c. Whenever\n  c grows beyond its previous maximum size f is called as above for each item\n  beyond the maximum size. Nothing happens when c shrinks.\n\n  See also: the javelin.core/cell-doseq macro.\n\n  Consider:\n\n      (def things (cell [:a :b :c]))\n      (cell-doseq*\n        things\n        (fn doit [x]\n          (prn :creating @x)\n          (add-watch x nil #(prn :updating %3 %4))))\n\n      ;; the following is printed:\n\n      :creating :a\n      :creating :b\n      :creating :c\n\n  Shrink things by removing the last item:\n\n      (swap! things pop)\n\n      ;; the following is printed (because the 3rd item in things is now nil,\n      ;; since things only contains 2 items) -- note that the doit function is\n      ;; not called (or we would see a :creating message):\n\n      :updating :c nil\n\n  Grow things such that it is one item larger than it ever was:\n\n      (swap! things into [:u :v])\n\n      ;; the following is printed (because things now has 4 items, so the 3rd\n      ;; item is now :u and the max size increases by one with the new item :v):\n\n      :updating nil :u\n      :creating :v\n\n  A weird imagination is most useful to gain full advantage of all the features."],
null)),$APP.C(QPd,new $APP.h(null,5,[$APP.Oy,new $APP.ng(null,new $APP.h(null,7,[EPd,"null",IOd,"null",zPd,"null",$APP.Xs,"null",$APP.jVa,"null",$APP.gIa,"null",$APP.vt,"null"],null),null),$APP.Sv,$APP.Xt,$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,11,5,$APP.O,[$APP.Rs,$APP.yw,hPd,$APP.VVa,$APP.Zt,ZPd,dQd,$APP.Jya,$APP.EHa,POd,iPd],null))),$APP.Ds,new $APP.ng(null,new $APP.h(null,7,[EPd,"null",IOd,"null",zPd,"null",$APP.Xs,"null",$APP.jVa,"null",$APP.gIa,"null",$APP.vt,"null"],null),null),$APP.S,
"Positional factory function for javelin.core/Cell."],null)),$APP.C(VOd,new $APP.h(null,3,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,aPd],null))),$APP.S,"Unlinks this Cell from the cell graph and resets all internal state. Watches\n  are preserved when keep-watches? is true, otherwise they are all removed.",$APP.Xy,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.At],
null),new $APP.N(null,2,5,$APP.O,[$APP.At,aPd],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,aPd],null)),$APP.Ox,$APP.Q(null,null)],null)],null)),$APP.C(nPd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[dQd],null))),$APP.S,"Calls the thunk with no arguments within a transaction. Propagation of\n  updates to formula cells is deferred until the transaction is complete.\n  Input cells *will* update during the transaction. Transactions may be\n  nested.\n\n  See also: the javelin.core/dosync macro."],
null)),$APP.C(hQd,new $APP.h(null,2,[$APP.U,$APP.Q($APP.P,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null))),$APP.S,"If x is a Cell dereferences x and returns the value, otherwise returns x."],null)),$APP.C(YPd,new $APP.h(null,1,[$APP.yt,!0],null))],[new $APP.h(null,3,[$APP.T,$Pd,$APP.X,K7,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,$APP.Qu],null),new $APP.N(null,3,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt],null),new $APP.N(null,
4,5,$APP.O,[$APP.At,$APP.Qu,$APP.Zt,H7],null)),$APP.S,"Given a Cell and optional formula function f and the cells f depends on,\n  sources, updates the formula for this cell in place. If f and/or sources\n  is not spcified they are set to nil."],null)],null),new $APP.h(null,3,[$APP.T,TOd,$APP.X,function(a,b){return $APP.L7.j($APP.Hd,b)(a)},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.Qu],null)),$APP.S,"Returns a new lens whose value is the same as c's with update function f.\n  This is equivalent to ((formula identity f) c)."],
null)],null),new $APP.h(null,3,[$APP.T,lQd,$APP.X,gOd,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),$APP.S,"Returns c if c is a lens, nil otherwise."],null)],null),new $APP.h(null,3,[$APP.T,SPd,$APP.X,fOd,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),$APP.S,"Returns c if c is a formula cell, nil otherwise."],null)],null),new $APP.h(null,3,[$APP.T,$APP.G7,$APP.X,$APP.L7,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,
1,5,$APP.O,[$APP.Qu],null),new $APP.N(null,2,5,$APP.O,[$APP.Qu,H7],null)),$APP.S,"Returns a function that returns a formula cell with f as its formula, and\n  if updatefn is provided the returned cell is a lens.\n\n  See also: the javelin.core/cell\x3d macro.\n\n      (def x (cell 100))\n      (def y (cell 200))\n\n      (def z1 (cell\x3d (+ x y)))\n      (def z2 ((formula +) x y))\n\n  The formula cells z1 and z2 are equivalent."],null)],null),new $APP.h(null,3,[$APP.T,TPd,$APP.X,C7,$APP.l,$APP.M],
null),new $APP.h(null,3,[$APP.T,tPd,$APP.X,$APP.L7,$APP.l,$APP.M],null),new $APP.h(null,3,[$APP.T,FPd,$APP.X,function(a){var b=$APP.A7(a);return $APP.n($APP.n(b)?a.constant:b)?a:null},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),$APP.S,"Returns c if c is a constant formula cell, nil otherwise."],null)],null),new $APP.h(null,3,[$APP.T,jQd,$APP.X,nQd,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.Hya],null)),$APP.S,"Given a number of cells, returns a formula cell whose value is a seq of\n  values from cells that changed in the last update. Note that multiple cells\n  may update atomically, which is why the formula's value is a seq.\n\n  Consider:\n\n      (def a (cell {:x 1 :y 2}))\n      (def x (cell\x3d (:x a)))\n      (def y (cell\x3d (:y a)))\n      (def z (alts! x y))\n\n  then,\n\n      (deref z) ;\x3d\x3e (1 2)\n\n      (swap! a assoc :x 42)\n      (deref z) ;\x3d\x3e (42)\n\n      (reset! a {:x 10 :y 20})\n      (deref z) ;\x3d\x3e (10 20)\n  "],
null)],null),new $APP.h(null,3,[$APP.T,gPd,$APP.X,function(a,b){var c=function(){var d=$APP.L7.o($APP.t);return d.o?d.o(b):d.call(null,b)}();return $APP.Mg.j(function(d){var e=$APP.L7.o($APP.Lk.j(a,bOd));return e.j?e.j(c,d):e.call(null,c,d)},$APP.pj.j(0,$APP.B($APP.Cb(c))))},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Qu,$APP.Pu],null)),$APP.S,"Given a function f and a cell c that contains a seqable collection of items,\n  returns a seq of formula cells such that the ith formula cell is equivalent\n  to (cell\x3d (f (nth c i)))."],
null)],null),new $APP.h(null,3,[$APP.T,SOd,$APP.X,function(a,b){a.state=b;return K7.o(a)},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.mv],null)),$APP.S,"Converts c to an input cell in place, setting its contents to x. It's okay\n  if c was already an input cell. Changes will be propagated to any cells that\n  depend on c."],null)],null),new $APP.h(null,3,[$APP.T,PPd,$APP.X,$APP.M7,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null),
new $APP.N(null,3,5,$APP.O,[$APP.mv,$APP.vh,new $APP.h(null,1,[$APP.et,new $APP.N(null,1,5,$APP.O,[$APP.Rs],null)],null)],null)),$APP.S,"Returns a new input cell containing value x. The :meta option can be used\n  to create the cell with the given metadata map."],null)],null),new $APP.h(null,3,[$APP.T,lPd,$APP.X,$APP.A7,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),$APP.S,"Returns c if c is a Cell, nil otherwise."],null)],null),new $APP.h(null,3,[$APP.T,mQd,$APP.X,
function(a,b){var c=$APP.Zg.o(0),d=$APP.L7.o(function(e){e=$APP.B(e);if($APP.Cb(c)<e){for(var f=e-$APP.Cb(c),k=0;;)if(k<f){var m=k+$APP.Cb(c);var q=$APP.L7.o(bOd);m=q.j?q.j(a,m):q.call(null,a,m);b.o?b.o(m):b.call(null,m);k+=1}else break;return $APP.Le(c,e)}return null});return d.o?d.o(a):d.call(null,a)},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Pu,$APP.Qu],null)),$APP.S,"Given a function f and a cell c that contains a seqable collection of items,\n  calls f for side effects once for each item in c, passing one argument: a\n  formula cell equivalent to (cell\x3d (nth c i)) for the ith item in c. Whenever\n  c grows beyond its previous maximum size f is called as above for each item\n  beyond the maximum size. Nothing happens when c shrinks.\n\n  See also: the javelin.core/cell-doseq macro.\n\n  Consider:\n\n      (def things (cell [:a :b :c]))\n      (cell-doseq*\n        things\n        (fn doit [x]\n          (prn :creating @x)\n          (add-watch x nil #(prn :updating %3 %4))))\n\n      ;; the following is printed:\n\n      :creating :a\n      :creating :b\n      :creating :c\n\n  Shrink things by removing the last item:\n\n      (swap! things pop)\n\n      ;; the following is printed (because the 3rd item in things is now nil,\n      ;; since things only contains 2 items) -- note that the doit function is\n      ;; not called (or we would see a :creating message):\n\n      :updating :c nil\n\n  Grow things such that it is one item larger than it ever was:\n\n      (swap! things into [:u :v])\n\n      ;; the following is printed (because things now has 4 items, so the 3rd\n      ;; item is now :u and the max size increases by one with the new item :v):\n\n      :updating nil :u\n      :creating :v\n\n  A weird imagination is most useful to gain full advantage of all the features."],
null)],null),new $APP.h(null,3,[$APP.T,kPd,$APP.X,function(a,b,c,d,e,f,k,m,q,u,v){return new C7(a,b,c,d,e,f,k,m,q,u,v)},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,11,5,$APP.O,[$APP.Rs,$APP.yw,hPd,$APP.VVa,$APP.Zt,ZPd,dQd,$APP.Jya,$APP.EHa,POd,iPd],null)),$APP.S,"Positional factory function for javelin.core/Cell."],null)],null),new $APP.h(null,3,[$APP.T,DPd,$APP.X,J7,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.At],null),new $APP.N(null,2,5,$APP.O,[$APP.At,
aPd],null)),$APP.S,"Unlinks this Cell from the cell graph and resets all internal state. Watches\n  are preserved when keep-watches? is true, otherwise they are all removed."],null)],null),new $APP.h(null,3,[$APP.T,GPd,$APP.X,function(a){if($APP.n(B7))return a.M?a.M():a.call(null);var b=B7;B7=[];try{a.M?a.M():a.call(null);var c=a=B7;B7=null;try{return $Nd(a)}finally{B7=c}}finally{B7=b}},$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[dQd],null)),$APP.S,"Calls the thunk with no arguments within a transaction. Propagation of\n  updates to formula cells is deferred until the transaction is complete.\n  Input cells *will* update during the transaction. Transactions may be\n  nested.\n\n  See also: the javelin.core/dosync macro."],
null)],null),new $APP.h(null,3,[$APP.T,aQd,$APP.X,aOd,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null)),$APP.S,"If x is a Cell dereferences x and returns the value, otherwise returns x."],null)],null),new $APP.h(null,3,[$APP.T,xPd,$APP.X,hOd,$APP.l,new $APP.h(null,2,[$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),$APP.S,"Returns c if c is an input cell, nil otherwise."],null)],null)]),N7),MPd,bQd,$APP.z([WPd,function(){var a=new $APP.qc(function(){return X7},
UOd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,WPd,!0,"sci/configs/hoplon/javelin.cljs",19,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,325,325,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.vh,$APP.Qw],null)),"Evaluates the body within a Javelin transaction. Propagation of updates\n  to formula cells is deferred until the transaction is complete. Input\n  cells *will* update during the transaction. Transactions may be nested.",
$APP.n(X7)?X7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),$APP.ALa,function(){var a=new $APP.qc(function(){return O7},wPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,$APP.ALa,
!0,"sci/configs/hoplon/javelin.cljs",21,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.Ew,jPd],null),$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.Ew,jPd],null),$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,219,219,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.Ew,jPd],null),$APP.vh,$APP.Qw],null)),
"Binds resource to binding and evaluates body.  Then, returns\n  resource.  It's a cross between doto and with-open.",$APP.n(O7)?O7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),JOd,function(){var a=new $APP.qc(function(){return P7},XOd,$APP.$f([$APP.Ck,
$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,JOd,!0,"sci/configs/hoplon/javelin.cljs",18,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,4,$APP.Wv,4,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,3,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww],null),new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww,$APP.Qu],null)],null),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww],null),new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww,$APP.Qu],null)),$APP.Ox,
$APP.Q(null,null)],null),1,225,225,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww],null),new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Ww,$APP.Qu],null)),null,$APP.n(P7)?P7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),OPd,function(){var a=
new $APP.qc(function(){return R7},eQd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,OPd,!0,"sci/configs/hoplon/javelin.cljs",17,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,5,$APP.Wv,5,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null),new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Cz,$APP.Ww],null)],null),$APP.U,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null),
new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Cz,$APP.Ww],null)),$APP.Ox,$APP.Q(null,null)],null),1,239,239,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null),new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Cz,$APP.Ww],null)),null,$APP.n(R7)?R7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=
$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),ePd,function(){var a=new $APP.qc(function(){return V7},ZOd,$APP.$f([$APP.Mm,$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[!0,I7,ePd,!0,"sci/configs/hoplon/javelin.cljs",33,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.ww,$APP.Pu],null),$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,
5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.ww,$APP.Pu],null),$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,313,313,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,2,5,$APP.O,[$APP.ww,$APP.Pu],null),$APP.vh,$APP.Qw],null)),null,$APP.n(V7)?V7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=
$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),$Od,function(){var a=new $APP.qc(function(){return W7},NPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,$Od,!0,"sci/configs/hoplon/javelin.cljs",21,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,new $APP.N(null,4,5,$APP.O,[$APP.ww,$APP.Pu,$APP.vh,$APP.ax],null),$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,
5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,4,5,$APP.O,[$APP.ww,$APP.Pu,$APP.vh,$APP.ax],null),$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,318,318,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,new $APP.N(null,4,5,$APP.O,[$APP.ww,$APP.Pu,$APP.vh,$APP.ax],null),$APP.vh,$APP.Qw],null)),null,$APP.n(W7)?W7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?
$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),LOd,function(){var a=new $APP.qc(function(){return S7},WOd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,LOd,!0,"sci/configs/hoplon/javelin.cljs",18,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,4,$APP.Wv,4,$APP.mz,new $APP.N(null,1,5,$APP.O,[new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null)],null),$APP.U,$APP.Q(new $APP.N(null,
4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null),new $APP.N(null,6,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Cz,$APP.vh,new $APP.N(null,2,5,$APP.O,[$APP.Ww,$APP.Qu],null)],null)),$APP.Ox,$APP.Q(null,null)],null),1,243,243,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Ww],null),new $APP.N(null,6,5,$APP.O,[$APP.Ol,$APP.It,$APP.uy,$APP.Cz,$APP.vh,new $APP.N(null,2,5,$APP.O,[$APP.Ww,$APP.Qu],null)],null)),null,$APP.n(S7)?S7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);
var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),cQd,function(){var a=new $APP.qc(function(){return Q7},KPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,cQd,!0,"sci/configs/hoplon/javelin.cljs",23,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,5,$APP.Wv,5,$APP.mz,
new $APP.N(null,2,5,$APP.O,[new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww],null),new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww,H7],null)],null),$APP.U,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww],null),new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww,H7],null)),$APP.Ox,$APP.Q(null,null)],null),1,232,232,$APP.Q(new $APP.N(null,4,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww],null),new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.Pu,$APP.Ww,
H7],null)),null,$APP.n(Q7)?Q7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),dPd,function(){var a=new $APP.qc(function(){return T7},vPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,
dPd,!0,"sci/configs/hoplon/javelin.cljs",23,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,rPd,$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,rPd,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,252,252,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,rPd,$APP.vh,$APP.Qw],null)),"ALPHA: this macro may change.\n\n  Given a vector of dependencies and one or more body expressions, emits a\n  form that will produce a formula cell. The dependencies must be names that\n  will be re-bound to their values within the body. No code walking is done.\n  The value of the formula cell is computed by evaluating the body expressions\n  whenever any of the dependencies change.\n\n  Note: the dependencies need not be cells.\n\n  E.g.\n      (def x 100)\n      (def y (cell 200))\n      (def z (cell\x3d (inc y)))\n\n      (def c (formula-of [x y z] (+ x y z)))\n\n      (deref c) ;\x3d\x3e 501\n\n      (swap! y inc)\n      (deref c) ;\x3d\x3e 503\n  ",
$APP.n(T7)?T7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),BPd,function(){var a=new $APP.qc(function(){return U7},pPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,BPd,!0,"sci/configs/hoplon/javelin.cljs",
21,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,$APP.ww,$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.ww,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,280,280,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.ww,$APP.vh,$APP.Qw],null)),"ALPHA: this macro may change.\n\n  Given a vector of binding-form/dependency pairs and one or more body\n  expressions, emits a form that will produce a formula cell. Each binding\n  form is bound to the value of the corresponding dependency within the body.\n  No code walking is done. The value of the formula cell is computed by\n  evaluating the body expressions whenever any of the dependencies change.\n\n  Note: the depdendency expressions are evaluated only once, when the formula\n  cell is created, and they need not evaluate to javelin cells.\n\n  E.g.\n      (def a (cell 42))\n      (def b (cell {:x 100 :y 200}))\n\n      (def c (formulet [v (cell\x3d (inc a))\n                        w (+ 1 2)\n                        {:keys [x y]} b]\n                (+ v w x y)))\n\n      (deref c) ;\x3d\x3e 346\n\n      (swap! a inc)\n      (deref c) ;\x3d\x3e 347\n  ",
$APP.n(U7)?U7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),MOd,function(){var a=new $APP.qc(function(){return Y7},yPd,$APP.$f([$APP.Ck,$APP.T,$APP.Rk,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[I7,MOd,!0,"sci/configs/hoplon/javelin.cljs",
23,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Ol,$APP.It,$APP.ww,$APP.Qw)],null),$APP.U,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.ww,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,332,332,$APP.Q(new $APP.N(null,5,5,$APP.O,[$APP.Ol,$APP.It,$APP.ww,$APP.vh,$APP.Qw],null)),"Takes a vector of binding-form/collection-cell pairs and one or more body\n  expressions, similar to clojure.core/doseq. Iterating over the collection\n  cells produces a sequence of items that may grow, shrink, or update over\n  time. Whenever this sequence grows the body expressions are evaluated (for\n  side effects) exactly once for each new location in the sequence. Bindings\n  are bound to cells that refer to the item at that location.\n\n  Consider:\n\n      (def things (cell [{:x :a} {:x :b} {:x :c}]))\n\n      (cell-doseq [{:keys [x]} things]\n        (prn :creating @x)\n        (add-watch x nil #(prn :updating %3 %4)))\n\n      ;; the following is printed -- note that x is a cell:\n\n      :creating :a\n      :creating :b\n      :creating :c\n\n  Shrink things by removing the last item:\n\n      (swap! things pop)\n\n      ;; the following is printed (because the 3rd item in things is now nil,\n      ;; since things only contains 2 items) -- note that the doit function is\n      ;; not called (or we would see a :creating message):\n\n      :updating :c nil\n\n  Grow things such that it is one item larger than it ever was:\n\n      (swap! things into [{:x :u} {:x :v}])\n\n      ;; the following is printed (because things now has 4 items, so the 3rd\n      ;; item is now {:x :u} and the max size increases by one with the new\n      ;; item {:x :v}):\n\n      :updating nil :u\n      :creating :v\n\n  A weird imagination is most useful to gain full advantage of all the features.",
$APP.n(Y7)?Y7.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,N7,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}()]));$APP.bn(new $APP.h(null,1,[$APP.Wk,new $APP.h(null,1,[iQd,pQd],null)],null));
}).call(this);