(function(){
'use strict';var snc=function(a,b){var c=$APP.baa(b);const d=c?b:arguments;for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},tnc=function(a,b){return $APP.opa(a,b)},unc=function(a,b){b=$APP.Vm(a,$APP.Sh("(keys (ns-map '%s))","%s",b));b=$APP.Mg.j(function(c){return["`",$APP.p.o(c)].join("")},b);b=["[",$APP.Mk.j(" ",b),"]"].join("");a=$APP.Tpa(a,b);return $APP.bm.j(function(c){return $APP.Zh($APP.p.o(c),"nbb.internal")},a)},wnc=function(a,b,c){c=$APP.Xh.j(c,/\//);$APP.F.A(c,0,null);
var d=$APP.F.A(c,1,null),e=$APP.Vm(a,$APP.Yg.B($APP.z([$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,vnc,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.UCa,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.P,null,1,null),new $APP.I(null,b,null,1,null)))),null,1,null)))),null,1,null))))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,
$APP.CIa,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.DEa,null,1,null),new $APP.I(null,vnc,null,1,null)))),null,1,null),$APP.z([new $APP.I(null,vnc,null,1,null)])))),null,1,null)]))))])));if($APP.n(e)&&(a=$APP.n(d)?function(){var m=$APP.Fa(d,"."),q=$APP.Xh.j(d,/\./);m=m?q:$APP.sg(q);return new $APP.N(null,2,5,$APP.O,[[$APP.p.o(b),"/",$APP.t(m)?[$APP.Mk.j(".",m),"."].join(""):null].join(""),$APP.Ge.A(snc,e,m)],null)}():new $APP.N(null,2,5,$APP.O,[[$APP.p.o(b),"/"].join(""),
e],null),$APP.n(a))){var f=$APP.F.A(a,0,null),k=$APP.F.A(a,1,null);a=function(){for(var m=k,q=$APP.ff;;)if($APP.n(m)){var u=Object.getPrototypeOf(m);q=$APP.Mf.j(q,Object.getOwnPropertyNames(m));m=u}else return q}();return $APP.Mg.j(function(m){return new $APP.N(null,2,5,$APP.O,[null,[$APP.p.o(f),$APP.p.o(m)].join("")],null)},a)}return null},Anc=function(a){var b=$APP.ve(a);a=$APP.E.j(b,$APP.Ck);var c=$APP.E.j(b,$APP.am);try{var d=$APP.n(a)?tnc(c,$APP.Pg.o(a)):null,e=$APP.te([$APP.Yk,$APP.n(d)?d:$APP.Cb($APP.Yk)]);
$APP.xk(e);try{var f=function(){var da=$APP.Ni.o(b);return $APP.n(da)?da:$APP.Au.o(b)}();if($APP.n(f)){var k=$APP.Ia(f,"/"),m=k?function(){var da=$APP.Xh.j(f,/\//);da=da==null?null:$APP.w(da);return da==null?null:$APP.Pg.o(da)}():null,q=unc(c,$APP.Tpa(c,"(ns-name *ns*)")),u=$APP.Mg.j(function(da){return new $APP.N(null,3,5,$APP.O,[$APP.de(da),$APP.tg(da),xnc],null)},q),v=$APP.Tpa(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),y=$APP.ug($APP.jg(v),$APP.hg(v)),A=$APP.lj.o($APP.$e.B(function(da){var oa=
$APP.E.j(v,da);da=$APP.Vm(c,$APP.Sh("(keys (ns-publics '%s))","%s",oa));return $APP.Mg.j(function(ka){return new $APP.N(null,3,5,$APP.O,[$APP.p.o(oa),$APP.p.o(ka),ync],null)},da)},$APP.z([$APP.hg(v)]))),D=$APP.Mg.j(function(da){return new $APP.N(null,3,5,$APP.O,[$APP.p.o(da),null,ync],null)},$APP.Tpa(c,"(all-ns)")),H=k?wnc(c,m,f):null,K=$APP.n(H)?null:k?function(){var da=$APP.E.A(v,m,m),oa=$APP.Vm(c,$APP.Sh("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))",
"%s",da));return $APP.Mg.j(function(ka){return new $APP.N(null,3,5,$APP.O,[$APP.p.o(da),$APP.p.o(ka),ync],null)},oa)}():null,V=$APP.R.B(u,A,$APP.z([D,K])),Y=$APP.Kk.j(function(da){var oa=$APP.F.A(da,0,null);var ka=$APP.F.A(da,1,null),ea=$APP.F.A(da,2,null);da=$APP.Fg(f);ea=(ea=$APP.G.j(xnc,ea))?$APP.Dg(da,ka):ea;ea=$APP.n(ea)?new $APP.N(null,2,5,$APP.O,[oa,ka],null):null;$APP.n(ea)?oa=ea:$APP.n(oa)?(ea=$APP.n($APP.Dg(da,[$APP.p.o($APP.E.j(y,$APP.Pg.o(oa))),"/",$APP.p.o(ka)].join("")))?new $APP.N(null,
2,5,$APP.O,[oa,[$APP.p.o($APP.E.j(y,$APP.Pg.o(oa))),"/",$APP.p.o(ka)].join("")],null):null,oa=$APP.n(ea)?ea:$APP.n($APP.Dg(da,[$APP.p.o(oa),"/",$APP.p.o(ka)].join("")))?new $APP.N(null,2,5,$APP.O,[oa,[$APP.p.o(oa),"/",$APP.p.o(ka)].join("")],null):null):oa=null;return oa},V),Z=$APP.R.j(Y,H),aa=$APP.Fd($APP.Zr.o($APP.Mg.j(function(da){var oa=$APP.F.A(da,0,null);da=$APP.F.A(da,1,null);da=new $APP.h(null,1,["candidate",$APP.p.o(da)],null);return $APP.n(oa)?$APP.lg.A(da,"ns",$APP.p.o(oa)):da},Z)));return new $APP.h(null,
2,[znc,aa,$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null)],null)}return new $APP.h(null,1,[$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null)],null)}finally{$APP.yk()}}catch(da){return console.error("ERROR",da),new $APP.h(null,2,[znc,$APP.ff,$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null)],null)}},Bnc=function(a,b){return a.replace("%s",b)},Gnc=function(a){var b=$APP.ve(a);a=$APP.E.j(b,$APP.Ck);var c=$APP.E.j(b,$APP.Dx);b=$APP.E.j(b,$APP.am);if($APP.db(c))return new $APP.h(null,2,[$APP.ms,new $APP.N(null,
2,5,$APP.O,["no-eldoc","done"],null),$APP.NQa,"Message should contain a `sym`"],null);a=Bnc(Bnc("(when-let [the-var (ns-resolve '%s '%s)]\n               (meta the-var))",a),c);try{var d=new $APP.N(null,2,5,$APP.O,[Cnc,$APP.Tpa(b,a)],null)}catch(m){d=new $APP.N(null,2,5,$APP.O,[Dnc,$APP.p.o(m)],null)}c=$APP.F.A(d,0,null);var e=$APP.F.A(d,1,null),f=$APP.ve(e);b=$APP.E.j(f,$APP.S);a=$APP.E.j(f,$APP.wi);d=$APP.E.j(f,$APP.xi);var k=$APP.E.j(f,$APP.T);f=$APP.E.j(f,$APP.U);return $APP.n($APP.n(k)?$APP.G.j(c,
Cnc):k)?(c=new $APP.h(null,6,[$APP.Ck,function(){var m=e==null?null:$APP.Ck.o(e);return m==null?null:m.name}(),$APP.U,$APP.Yg.B($APP.z([f])),Enc,$APP.Jk.j(function(m){return $APP.Jk.j($APP.p,m)},f),Fnc,$APP.Ge.j($APP.fba,f).join("\n"),$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null),$APP.T,k],null),c=$APP.n(b)?$APP.lg.A(c,$APP.S,b):c,a=$APP.n(a)?$APP.lg.A(c,$APP.wi,a):c,$APP.n(d)?$APP.lg.A(a,$APP.xi,d):a):new $APP.h(null,1,[$APP.ms,new $APP.N(null,2,5,$APP.O,["done","no-eldoc"],null)],null)},nR=
function(a,b){var c=$APP.ve(a);a=$APP.E.j(c,$APP.Vk);var d=$APP.E.j(c,$APP.Xza);c=$APP.E.j(c,Hnc);b=$APP.ve(b);var e=$APP.E.j(b,$APP.Ck);e=$APP.n(e)?e:$APP.p.o($APP.Cb(Inc));a=$APP.ri.j($APP.lg.B(b,$APP.Vk,a,$APP.z([$APP.Xza,d,$APP.Ck,e])),$APP.am);return $APP.n(c)?c.o?c.o(a):c.call(null,a):window.ws_nrepl.send($APP.p.o(a))},Jnc=function(a){var b=Gnc($APP.lg.A(a,$APP.am,$APP.mk()));return nR(a,b)},znc=new $APP.J(null,"completions","completions",-190930179),Cnc=new $APP.J("sci.nrepl.info","success",
"sci.nrepl.info/success",-493835426),vnc=new $APP.r(null,"resolved__76211__auto__","resolved__76211__auto__",-936128367,null),Knc=new $APP.J(null,"load-file","load-file",-424586670),xnc=new $APP.J(null,"unqualified","unqualified",-98904653),Lnc=new $APP.J(null,"clone","clone",711747572),Mnc=new $APP.J(null,"complete","complete",-500388775),Nnc=new $APP.J(null,"lookup","lookup",1225356838),Fnc=new $APP.J(null,"arglists-str","arglists-str",1439431437),Onc=new $APP.J(null,"describe","describe",1369790582),
Pnc=new $APP.J(null,"ops","ops",1237330063),Qnc=new $APP.J("sci.nrepl.server","error","sci.nrepl.server/error",855827645),Rnc=new $APP.J(null,"versions","versions",536521978),ync=new $APP.J(null,"qualified","qualified",-2065109343),Snc=new $APP.J("sci.nrepl.server","success","sci.nrepl.server/success",-67357591),Enc=new $APP.J(null,"eldoc","eldoc",-1321421900),Hnc=new $APP.J(null,"send-fn","send-fn",351002041),Dnc=new $APP.J("sci.nrepl.info","error","sci.nrepl.info/error",1267042764);var Inc=$APP.Oe($APP.Cb($APP.Yk)),Tnc=new $APP.h(null,6,[$APP.eUa,function(a){a=$APP.ve(a);var b=$APP.E.j(a,$APP.ft);try{var c=$APP.O;b:{var d=$APP.te([$APP.Yk,$APP.Cb(Inc)]);$APP.xk(d);try{var e=$APP.Kka(b);for(d=null;;){var f=$APP.mk();var k=$APP.Xpa(f,e);if($APP.G.j($APP.Wpa,k)){$APP.Pe(Inc,$APP.Cb($APP.Yk));var m=d;break b}d=$APP.Ypa($APP.mk(),k)}}finally{$APP.yk()}m=void 0}var q=new $APP.N(null,2,5,c,[Snc,m],null)}catch(u){q=new $APP.N(null,2,5,$APP.O,[Qnc,$APP.p.o(u)],null)}m=$APP.F.A(q,0,null);
q=$APP.F.A(q,1,null);m=m instanceof $APP.J?m.aa:null;switch(m){case "sci.nrepl.server/success":return nR(a,new $APP.h(null,1,[$APP.Kv,$APP.Yg.B($APP.z([q]))],null)),nR(a,new $APP.h(null,1,[$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null)],null));case "sci.nrepl.server/error":return nR(a,new $APP.h(null,1,[$APP.NQa,$APP.Yg.B($APP.z([q]))],null)),nR(a,new $APP.h(null,2,[$APP.noa,$APP.Yg.B($APP.z([q])),$APP.ms,new $APP.N(null,2,5,$APP.O,["error","done"],null)],null));default:throw Error(["No matching clause: ",
$APP.p.o(m)].join(""));}},$APP.Pt,Jnc,Enc,Jnc,Nnc,Jnc,Onc,function(a){return nR(a,new $APP.h(null,3,[Rnc,new $APP.h(null,1,["sci-nrepl",new $APP.h(null,3,"major 0 minor 0 incremental 1".split(" "),null)],null),Pnc,$APP.ug($APP.Mg.j($APP.tg,$APP.R.B($APP.hg(Tnc),new $APP.ng(null,new $APP.h(null,2,[Knc,null,Lnc,null],null),null),$APP.z([new $APP.ng(null,new $APP.h(null,1,["close",null],null),null)]))),$APP.Zi.o($APP.M)),$APP.ms,new $APP.N(null,1,5,$APP.O,["done"],null)],null))},Mnc,function(a){var b=
Anc($APP.lg.A(a,$APP.am,$APP.mk()));return nR(a,b)}],null);var Unc=window.SCITTLE_NREPL_WEBSOCKET_PORT;if($APP.n(Unc)){var Vnc=window,Wnc=WebSocket,Xnc;Xnc=["ws://",$APP.p.o(window.location.hostname),":",$APP.p.o(Unc),"/",$APP.p.o("_nrepl")].join("");Vnc.ws_nrepl=new Wnc(Xnc)}var Ync=window.ws_nrepl;
$APP.n(Ync)&&(Ync.onmessage=function(a){a=$APP.dB.o(a.data);var b=$APP.Fy.o(a);b=Tnc.o?Tnc.o(b):Tnc.call(null,b);return $APP.n(b)?b.o?b.o(a):b.call(null,a):nR(a,$APP.rh.B($APP.z([a,new $APP.h(null,2,[$APP.ms,new $APP.N(null,2,5,$APP.O,["error","done"],null),$APP.NQa,"unknown-op"],null)])))},Ync.onerror=function(a){return console.log(a)});
}).call(this);