(function(){
shadow$provide[2]=function(l,L,q){L.exports=ReactDOM};
shadow$provide[3]=function(l,L,q){L.exports=React};
'use strict';var hvc,jvc,kvc,pT,lvc,mvc,nvc,ovc,pvc,qvc,rvc,svc,tvc,uvc,vvc,rT,wvc,xvc,yvc,zvc,Avc,Bvc,tT,Cvc,Fvc,Hvc,Jvc,Lvc,Mvc,Nvc,Qvc,Tvc,wT,Uvc,Vvc,Wvc,Xvc,Zvc,cwc,dwc,fwc,jwc,kwc,mwc,nwc,owc,pwc,qwc,vwc,uwc,wwc,xwc,ywc,zwc,Cwc,Bwc,Ewc,Fwc,Gwc,Hwc,Iwc,Jwc,Kwc,Nwc,Qwc,Rwc,Swc,Twc,Wwc,Zwc,$wc,axc,bxc,cxc,dxc,exc,fxc,gxc,hxc,ixc,jxc,kxc,lxc,mxc,nxc,oxc,pxc,Owc,qxc,rxc,sxc,txc,uxc,vxc,wxc,Ivc,lwc,xxc,yxc,zxc,Evc,DT,Axc,Bxc,$vc,Cxc,Dxc,Exc,awc,Fxc,Gxc,Hxc,Ixc,Jxc,Kxc,Lxc,Mxc,Nxc,Oxc,Pxc,Qxc,Rxc,ET,
Sxc,Txc,Uxc,Vxc,Wxc,Xxc,Yxc,Zxc,$xc,ayc,byc,cyc,dyc,eyc,fyc,gyc,hyc,iyc,jyc,kyc,lyc,rwc,myc,nyc,oyc,pyc,qyc,ryc,syc,GT,tyc,uyc,vyc,Vwc,wyc,xyc,yyc,zyc,Ayc,Byc,Cyc,Dyc,Eyc,HT,Fyc,Gyc,Hyc,Uwc,Iyc,Jyc,Kyc,Lyc,bwc,Myc,hwc,Nyc;hvc=function(a){return $APP.B(a)<2?$APP.Th(a):[$APP.Th($APP.Eg.A(a,0,1)),$APP.Eg.j(a,1)].join("")};
jvc=function(a){if(typeof a==="string")return a;a=$APP.tg(a);var b=$APP.Xh.j(a,/-/),c=$APP.t(b);b=$APP.w(c);c=$APP.x(c);return $APP.n(ivc.o?ivc.o(b):ivc.call(null,b))?a:$APP.Ge.A($APP.p,b,$APP.Mg.j(hvc,c))};
kvc=function(a){var b=function(){var c=function(){var d=$APP.Wc(a);if(d){d=a.displayName;if($APP.n(d))return d;d=a.name;return typeof d==="string"&&$APP.t(d)?d:null}return d}();if($APP.n(c))return c;c=function(){var d=a!=null?a.Y&4096||$APP.lc===a.en?!0:!1:!1;return d?$APP.tg(a):d}();if($APP.n(c))return c;c=$APP.Yc(a);return $APP.gd(c)?$APP.T.o(c):null}();return $APP.n(b)?$APP.Sh($APP.p.o(b),"$","."):null};pT=function(a){return a instanceof $APP.J||a instanceof $APP.r};
lvc=function(a){if($APP.gd(a))try{var b=$APP.E.j(a,$APP.Ft)}catch(c){b=null}else b=null;return b};mvc=function(a){var b=$APP.Ft.o($APP.Yc(a));if(b!=null)return b;b=$APP.F.A(a,0,null);switch(b instanceof $APP.J?b.aa:null){case "\x3e":case "f\x3e":return lvc($APP.F.A(a,2,null));case "r\x3e":return a=$APP.F.A(a,2,null),a==null?null:a.key;default:return lvc($APP.F.A(a,1,null))}};nvc=function(a){return setTimeout(a,16)};ovc=function(a,b){return a.Gp-b.Gp};pvc=function(){return null};
qvc=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.M?d.M():d.call(null);c+=1}else return null};rvc=function(a,b,c){b.push(c);return a.schedule()};svc=function(){this.jo=!1};tvc=function(a){if($APP.n(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return $APP.qT.queue_render(a)};
uvc=function(a){if(a!=null&&a.RA!=null)a=a.id;else{var b=uvc[$APP.ha(a==null?null:a)];if(b!=null)a=b.o?b.o(a):b.call(null,a);else if(b=uvc._,b!=null)a=b.o?b.o(a):b.call(null,a);else throw $APP.kb("Compiler.get-id",a);}return a};vvc=function(a,b,c){if(a!=null&&a.Rv!=null)a=a.Rv(a,b,c);else{var d=vvc[$APP.ha(a==null?null:a)];if(d!=null)a=d.A?d.A(a,b,c):d.call(null,a,b,c);else if(d=vvc._,d!=null)a=d.A?d.A(a,b,c):d.call(null,a,b,c);else throw $APP.kb("Compiler.parse-tag",a);}return a};
rT=function(a,b){if(a!=null&&a.Pv!=null)a=a.Pv(a,b);else{var c=rT[$APP.ha(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=rT._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.kb("Compiler.as-element",a);}return a};
wvc=function(a,b,c,d,e){if(a!=null&&a.Qv!=null)a=a.Qv(a,b,c,d,e);else{var f=wvc[$APP.ha(a==null?null:a)];if(f!=null)a=f.ba?f.ba(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=wvc._,f!=null)a=f.ba?f.ba(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.kb("Compiler.make-element",a);}return a};xvc=function(){return sT!=null};
yvc=function(a,b){b.$o=null;var c=sT;sT=b;try{var d=a.M?a.M():a.call(null)}finally{sT=c}a=b.$o;b.Gj=!1;a:{c=b.Kk;var e=a==null?0:a.length,f=e===(c==null?0:c.length);if(f){for(f=0;;){var k=f===e;if(k){c=k;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}c=void 0}else c=f}c||b._update_watching(a);return d};zvc=function(a){var b=sT;if(b!=null){var c=b.$o;c==null?b.$o=[a]:c.push(a)}};Avc=function(a,b,c){b=$APP.lg.A(a.watches,b,c);a.watches=b;return a.ms=null};
Bvc=function(a,b){b=$APP.ri.j(a.watches,b);a.watches=b;return a.ms=null};tT=function(a,b,c){var d=a.ms;d=d==null?a.ms=$APP.Gd(function(q,u,v){q.push(u);q.push(v);return q},[],a.watches):d;for(var e=d.length,f=0;;)if(f<e){var k=d[f],m=d[f+1];m.F?m.F(k,a,b,c):m.call(null,k,a,b,c);f=2+f}else return null};Cvc=function(a,b,c,d){$APP.Sb(a,["#object[reagent.ratom.",$APP.p.o(c)," "].join(""));c=sT;sT=null;sT=c;$APP.Kg(d,a,b);return $APP.Sb(a,"]")};
$APP.Dvc=function(a,b,c,d){this.state=a;this.meta=b;this.Ik=c;this.watches=d;this.V=2154201088;this.Y=114690};
Fvc=function(a,b,c,d,e){var f=b.Kq;f=f==null?$APP.M:f;var k=f.j?f.j(c,null):f.call(null,c,null);if(k!=null)return $APP.Cb(k);if(sT==null)return a.M?a.M():a.call(null);k=function(){function q(u){var v=$APP.ri.j(b.Kq,c);b.Kq=v;d!=null&&(d.Em=null);return e!=null?e.o?e.o(u):e.call(null,u):null}return $APP.uT.A?$APP.uT.A(a,Evc,q):$APP.uT.call(null,a,Evc,q)}();var m=$APP.Cb(k);b.Kq=$APP.lg.A(f,c,k);d!=null&&(d.Em=k);return m};
$APP.Gvc=function(a,b,c){this.f=a;this.args=b;this.Em=c;this.V=2153807872;this.Y=0};Hvc=function(a,b){return new $APP.Gvc(a,b,null)};Jvc=function(a,b){var c=Hvc(a,b);a=function(){function d(){return c.Oa(null)}return $APP.uT.A?$APP.uT.A(d,Ivc,!0):$APP.uT.call(null,d,Ivc,!0)}();$APP.Cb(a);return a};$APP.Kvc=function(a,b,c,d,e){this.ad=a;this.path=b;this.Em=c;this.state=d;this.watches=e;this.V=2153807872;this.Y=114690};Lvc=function(a){a=a.destroy;return a==null?null:a.M?a.M():a.call(null)};
Mvc=function(a){var b=sT;return b==null?[]:Fvc(function(){return[]},b,a,null,Lvc)};$APP.vT=function(a){if(a!=null&&a.Mq!=null)a=a.Mq(a);else{var b=$APP.vT[$APP.ha(a==null?null:a)];if(b!=null)a=b.o?b.o(a):b.call(null,a);else if(b=$APP.vT._,b!=null)a=b.o?b.o(a):b.call(null,a);else throw $APP.kb("IDisposable.dispose!",a);}return a};Nvc=function(a,b,c,d){return a._handle_change(b,c,d)};
$APP.Ovc=function(a,b,c,d,e,f,k,m){this.f=a;this.state=b;this.Gj=c;this.ev=d;this.Kk=e;this.watches=f;this.Rh=k;this.cp=m;this.V=2153807872;this.Y=114690};Qvc=function(){for(;;){var a=Pvc;if(a==null)return null;Pvc=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};Tvc=function(a,b){var c=Rvc,d=Svc,e=yvc(a,d);d.Kk!=null&&(Svc=$APP.uT(null),d._set_opts(c),d.f=a,d.Rh=function(){return tvc.o?tvc.o(b):tvc.call(null,b)},b.cljsRatom=d);return e};
wT=function(a,b){var c=b.argv;if(c==null){c=$APP.O;a=a.constructor;a:{for(var d=$APP.Ja(b),e=d.length,f=$APP.M,k=0;;)if(k<e){var m=d[k];f=$APP.lg.A(f,$APP.Ng.o(m),$APP.Ka(b,m));k+=1}else{b=f;break a}b=void 0}b=new $APP.N(null,2,5,c,[a,b],null)}else b=c;return b};Uvc=function(a){var b;if(b=$APP.Wc(a))a=a==null?null:a.prototype,b=(a==null?null:a.Qj)!=null;return b};Vvc=function(a){var b;if(b=$APP.Wc(a))a=a==null?null:a.prototype,b=(a==null?null:a.render)!=null;return b};
Wvc=function(a,b){for(;;){var c=a.Qj,d=a.Vx===!0?c.call(a,a):function(){var e=wT(a,a.props);switch($APP.B(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.F.j(e,1));case 3:return c.call(a,$APP.F.j(e,1),$APP.F.j(e,2));case 4:return c.call(a,$APP.F.j(e,1),$APP.F.j(e,2),$APP.F.j(e,3));case 5:return c.call(a,$APP.F.j(e,1),$APP.F.j(e,2),$APP.F.j(e,3),$APP.F.j(e,4));default:return c.apply(a,$APP.Kl.o(e).slice(1))}}();if($APP.id(d))return rT(b,d);if($APP.rd(d))a.Qj=Uvc(d)?function(e,f,k,m,q){return function(){function u(y){var A=
null;if(arguments.length>0){A=0;for(var D=Array(arguments.length-0);A<D.length;)D[A]=arguments[A+0],++A;A=new $APP.rc(D,0,null)}return v.call(this,A)}function v(y){return rT(f,$APP.Ge.A($APP.Oq,q,y))}u.K=0;u.P=function(y){y=$APP.t(y);return v(y)};u.B=v;return u}()}(a,b,c,null,d):d;else return d}};
Xvc=function(a,b){switch(a instanceof $APP.J?a.aa:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;f!=null&&(c=$APP.F.A(f,1,null),c=$APP.gd(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Xx;d=d!=null?d:c.Xx=xT.o(null);return $APP.Le(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,wT(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,wT(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,wT(this,c))};case "shouldComponentUpdate":return function(c){var d=yT;if($APP.n(d))return d;d=this.props.argv;var e=c.argv,f=d==null||e==null;if(b==null){if(f)return f;try{return $APP.kg.j(d,e)}catch(k){return!1}}else return f?b.call(this,this,wT(this,this.props),wT(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,wT(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,wT(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,wT(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Ka(this,"cljsRatom");c!=null&&$APP.vT(c);this.cljsIsDirty=!1;return b==null?null:b.call(this,this)};
case "componentDidCatch":return function(c,d){return b.call(this,this,c,d)};default:return null}};Zvc=function(a){return $APP.Gd(function(b,c,d){return $APP.lg.A(b,$APP.Ng.o(Yvc(c)),d)},$APP.M,a)};
cwc=function(a,b){var c=function(){var k=$vc.o(a);return $APP.n(k)?k:$APP.vw.o(a)}(),d=$vc.o(a)==null,e=function(){var k=awc.o(a);if($APP.n(k))return k;k=kvc(c);return $APP.n(k)?k:$APP.p.o($APP.sj.o("reagent"))}(),f=$APP.Gd(function(k,m,q){var u=$APP.lg.A,v=Xvc(m,q);return u.call($APP.lg,k,m,$APP.n(v)?v:q)},$APP.M,a);return $APP.lg.B(f,awc,e,$APP.z([bwc,d,$vc,c,$APP.vw,function(){var k=this,m=$APP.Ka(k,"cljsRatom");k.cljsIsDirty=!1;return m==null?Tvc(function(){var q=zT;zT=k;try{var u=Wvc(k,b)}finally{zT=
q}return u},k):m._run(!1)}]))};dwc=function(a){return $APP.Gd(function(b,c,d){c=$APP.tg(c);b[c]=d;return b},{},a)};fwc=function(a,b){a=Zvc(a);a=$APP.rh.B($APP.z([ewc,a]));return cwc(a,b)};
jwc=function(a,b){function c(m,q,u){$APP.AT.Component.call(this,m,q,u);$APP.n(k)&&(k.j?k.j(this,m):k.call(null,this,m));$APP.n(f)&&(this.state=f.o?f.o(this):f.call(null,this));this.Gp=gwc+=1;return this}a=fwc(a,b);b=dwc($APP.Ge.B($APP.ri,a,awc,hwc,$APP.rm,$APP.z([$APP.vw,$vc,iwc])));var d=dwc($APP.mg(a,iwc)),e=awc.o(a),f=hwc.o(a),k=$APP.rm.o(a);$APP.uaa(c.prototype,$APP.AT.Component.prototype,b);$APP.n($APP.vw.o(a))&&(c.prototype.render=$APP.vw.o(a));$APP.n($vc.o(a))&&(c.prototype.Qj=$vc.o(a));$APP.n(bwc.o(a))&&
(c.prototype.Vx=bwc.o(a));$APP.uaa(c,$APP.AT.Component,d);$APP.n(e)&&(c.displayName=e,c.pn=e,c.Tx=function(m){return $APP.Sb(m,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.Jt=!0;return c.prototype.constructor=c};kwc=function(a,b,c){a=uvc(a);return b[a]=c};mwc=function(a,b){var c=$APP.Ka(a,uvc(b));c==null?Uvc(a)?a=kwc(b,a,a):(c=$APP.Yc(a),c=$APP.lg.A(c,lwc,a),c=jwc(c,b),a=kwc(b,a,c)):a=c;return a};
nwc=function(a,b){for(;;){var c=b.Qj,d=b.argv,e=$APP.Ge.j(c,d);if($APP.id(e))return rT(a,e);if($APP.rd(e))b.Qj=Uvc(e)?function(f,k,m,q,u,v){return function(){function y(D){var H=null;if(arguments.length>0){H=0;for(var K=Array(arguments.length-0);H<K.length;)K[H]=arguments[H+0],++H;H=new $APP.rc(K,0,null)}return A.call(this,H)}function A(D){return rT(f,$APP.Ge.A($APP.Oq,v,D))}y.K=0;y.P=function(D){D=$APP.t(D);return A(D)};y.B=A;return y}()}(a,b,c,null,d,e):e;else return e}};
owc=function(a,b){var c=b.argv,d=b.Qj;b=$APP.AT.useState(0);$APP.F.A(b,0,null);var e=$APP.F.A(b,1,null),f=$APP.AT.useRef();$APP.n(f.current)||function(){var m={forceUpdate:function(){return e.o?e.o($APP.Fc):e.call(null,$APP.Fc)}};m.Gp=gwc+=1;m.constructor=d;m.Qj=d;return f.current=m}();var k=f.current;b=$APP.Ka(k,"cljsRatom");$APP.AT.useEffect(function(){return function(){var m=$APP.Ka(k,"cljsRatom");return m==null?null:$APP.vT(m)}},[]);k.argv=c;k.cljsIsDirty=!1;return b==null?Tvc(function(){var m=
zT;zT=k;try{var q=nwc(a,k)}finally{zT=m}return q},k):b._run(!1)};pwc=function(a,b){a=a.argv;b=b.argv;var c=yT===!1;if(c)try{return $APP.G.j(a,b)}catch(d){return!1}else return c};qwc=function(a,b){function c(e){return owc(a,e)}var d=$APP.Ka(b,uvc(a));if($APP.n(d))return d;d=kvc(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.AT.memo(c,pwc);kwc(a,b,d);return d};
vwc=function(a,b,c,d){var e=$APP.ve($APP.M);e=$APP.E.j(e,rwc);if($APP.n(function(){var k=!(a===document.activeElement&&$APP.wd(swc,a.type)&&typeof b==="string"&&typeof c==="string");return k?k:twc}()))return d.qn=b,a.value=b,$APP.Wc(e)?e.o?e.o(b):e.call(null,b):null;var f=a.value;if($APP.kg.j(f,c))return $APP.qT.add_after_render(function(){var k=twc;twc=!0;try{return uwc.o?uwc.o(d):uwc.call(null,d)}finally{twc=k}});f=$APP.B(f)-a.selectionStart;f=$APP.B(b)-f;d.qn=b;a.value=b;$APP.Wc(e)&&(e.o?e.o(b):
e.call(null,b));a.selectionStart=f;return a.selectionEnd=f};uwc=function(a){if($APP.n(a.Fp)){a.Lt=!1;var b=a.Wx,c=a.qn,d=a.lq;return $APP.kg.j(b,c)?vwc(d,b,c,a):null}return null};wwc=function(a,b,c){a.qn=c.target.value;$APP.n(a.Lt)||(a.Lt=!0,$APP.qT.add_after_render(function(){return uwc(a)}));return b.o?b.o(c):b.call(null,c)};
xwc=function(a){var b=zT;if($APP.n(function(){var f=a!=null;return f?(f=a.hasOwnProperty("onChange"),$APP.n(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=c==null?"":c;var d=a.onChange,e=a.ref;$APP.n(b.Fp)||(b.Fp=!0,b.qn=c);$APP.n(b.Sv)||(b.Sv=$APP.Wc(e)?function(f){b.lq=f;return e.o?e.o(f):e.call(null,f)}:$APP.n($APP.n(e)?e.hasOwnProperty("current"):e)?function(f){b.lq=f;return e.current=f}:function(f){return b.lq=f});b.Wx=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return wwc(b,
d,f)};a.ref=b.Sv}};ywc=function(a){this.tag=a;this.className=this.id=null};$APP.BT=function(a){return new ywc(a)};zwc=function(a,b){return a.hasOwnProperty(b)?$APP.Ka(a,b):null};Cwc=function(a,b,c){if(pT(b)){var d=zwc(Awc,$APP.tg(b));d==null?(d=jvc(b),b=$APP.tg(b),b=Awc[b]=d):b=d}c=Bwc.o?Bwc.o(c):Bwc.call(null,c);a[b]=c;return a};
Bwc=function(a){return"object"!==$APP.ha(a)?a:pT(a)?$APP.tg(a):$APP.gd(a)?$APP.Gd(Cwc,{},a):$APP.bd(a)?$APP.ao(a):$APP.rd(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.rc(f,0,null)}return c.call(this,e)}function c(d){return $APP.Ge.j(a,d)}b.K=0;b.P=function(d){d=$APP.t(d);return c(d)};b.B=c;return b}():$APP.ao(a)};
Ewc=function(a,b,c){if(pT(b)){var d=zwc(Dwc,$APP.tg(b));d==null?(d=jvc(b),b=$APP.tg(b),b=Dwc[b]=d):b=d}c=Bwc(c);a[b]=c;return a};
Fwc=function(a){return"object"!==$APP.ha(a)?a:pT(a)?$APP.tg(a):$APP.gd(a)?$APP.Gd(Ewc,{},a):$APP.bd(a)?$APP.ao(a):$APP.rd(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.rc(f,0,null)}return c.call(this,e)}function c(d){return $APP.Ge.j(a,d)}b.K=0;b.P=function(d){d=$APP.t(d);return c(d)};b.B=c;return b}():$APP.ao(a)};
Gwc=function(a,b,c,d,e){switch($APP.B(b)-e){case 0:return $APP.AT.createElement(c,d);case 1:return $APP.AT.createElement(c,d,rT(a,$APP.F.A(b,e,null)));default:return $APP.AT.createElement.apply(null,$APP.Gd(function(f,k,m){k>=e&&f.push(rT(a,m));return f},[c,d],b))}};Hwc=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.$x=d};Iwc=function(a,b,c){a=mwc(a,c);c={};c.argv=b;b=mvc(b);b!=null&&(c.key=b);return $APP.AT.createElement(a,c)};
Jwc=function(a,b,c,d){var e={};e.Qj=a;e.argv=$APP.Wh.j(b,c);b=mvc(b);b!=null&&(e.key=b);return $APP.AT.createElement(qwc(d,a),e)};Kwc=function(a,b,c){return Vvc(a)?Iwc(a,b,c):Jwc(a,b,1,c)};Nwc=function(a,b){a=zwc(Lwc,b);if(a==null){var c=$APP.x($APP.Cg(Mwc,$APP.tg(b)));a=$APP.F.A(c,0,null);var d=$APP.F.A(c,1,null);c=$APP.F.A(c,2,null);c=c==null?null:$APP.Sh(c,/\./," ");var e=$APP.kg.j(-1,a.indexOf("-"));a=new Hwc(a,d,c,e);return Lwc[b]=a}return a};
Qwc=function(a,b,c,d){var e=a.tag,f=$APP.F.A(b,c,null),k=f==null||$APP.gd(f),m=function(){var v=k?f:null;var y=$APP.Dl.o(v);y=$APP.n(y)?$APP.lg.A(v,$APP.Dl,CT.o(y)):v;var A=a.id;v=a.className;A=A!=null&&$APP.Vk.o(y)==null?$APP.lg.A(y,$APP.Vk,A):y;if($APP.n(v)){var D=$APP.lg.A,H=CT.j,K=$APP.Dl.o(y);y=$APP.n(K)?K:Owc.o(y);v=D.call($APP.lg,A,$APP.Dl,H.call(CT,v,y))}else v=A;v=$APP.n(a.$x)?Fwc(v):Bwc(v);return $APP.n(v)?v:{}}();c+=k?1:0;a:switch(e){case "input":case "textarea":var q=!0;break a;default:q=
!1}if(q){q=lvc(f);var u=function(){var v=d.SA;if($APP.n(v))return v;v=jwc(Pwc,d);return d.SA=v}();return rT(d,$APP.C(new $APP.N(null,6,5,$APP.O,[u,b,e,m,c,d],null),$APP.rh.B($APP.z([$APP.n(q)?new $APP.h(null,1,[$APP.Ft,q],null):null,$APP.Yc(b)]))))}q=lvc($APP.Yc(b));q!=null&&(m.key=q);return wvc(d,b,e,m,c)};Rwc=function(a,b){return $APP.Kl.o($APP.Mg.j(function(c){return rT(b,c)},a))};
Swc=function(a,b,c){b==null&&console.error("vec-to-elem",$APP.Yg.B($APP.z([a])));var d=$APP.F.A(a,0,null);switch(d instanceof $APP.J?d.aa:null){case "\x3e":return c=$APP.F.A(a,1,null),Qwc(new Hwc(c,null,null,null),a,2,b);case "r\x3e":c=$APP.F.A(a,1,null);d=$APP.F.A(a,2,null);d=$APP.n(d)?d:{};var e=lvc($APP.Yc(a));e!=null&&(d.key=e);return wvc(b,a,c,d,3);case "f\x3e":return Jwc($APP.F.A(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.F.A(a,1,null),c=d==null||$APP.gd(d),d=Bwc(c?d:null),d=$APP.n(d)?d:
{},c=1+(c?1:0),e=mvc(a),e!=null&&(d.key=e),wvc(b,a,$APP.AT.Fragment,d,c);default:if(pT(d)||typeof d==="string")a:{for(;;){c=$APP.F.A(a,0,null);d=$APP.tg(c);e=d.indexOf("\x3e");switch(e){case -1:b=Qwc(vvc(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.C(new $APP.N(null,2,5,$APP.O,[$APP.Eg.A(d,0,e),$APP.lg.A($APP.C(a,null),0,$APP.Eg.j(d,e+1))],null),$APP.Yc(a));continue}break}b=void 0}else b=d instanceof ywc?Qwc(d,a,1,b):c.A?c.A(d,a,b):c.call(null,d,a,b);return b}};
Twc=function(a,b,c,d,e){this.zf=a;this.id=b;this.Fu=c;this.Yn=d;this.tA=e;this.V=393216;this.Y=0};Wwc=function(a){var b=$APP.sj.o("reagent-compiler"),c=$APP.n(Uwc.o(a))?Kwc:Iwc,d=$APP.E.A(a,Vwc,Nwc);return new Twc(a,b,c,d,$APP.M)};Zwc=function(a,b,c){var d=yT;yT=!0;try{return Xwc.render(a.M?a.M():a.call(null),b,function(){var e=yT;yT=!1;try{return $APP.$g.F(Ywc,$APP.lg,b,a),$APP.qT.flush_after_render(),c!=null?c.M?c.M():c.call(null):null}finally{yT=e}})}finally{yT=d}};$wc=function(a){return $APP.BT(a)};
axc=function(a){return $APP.vT(a)};bxc=function(a,b){return new $APP.Kvc(a,b,null,null,null)};cxc=function(a){return Wwc(a)};dxc=function(){return sT};exc=function(a){return a.generation};fxc=function(a){return a.ratomGeneration};gxc=function(a,b){return a.generation=b.ratomGeneration};hxc=function(a,b){return a.destroy=b};ixc=function(a){return a.destroy};jxc=function(){return!1};kxc=new $APP.r(null,"-generation","-generation",627658965,null);
lxc=new $APP.r("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);mxc=new $APP.r("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);nxc=new $APP.r("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);oxc=new $APP.r(null,"dispose!","dispose!",-395693497,null);pxc=new $APP.J(null,"componentWillUnmount","componentWillUnmount",1573788814);Owc=new $APP.J(null,"className","className",-1983287057);
qxc=new $APP.r(null,"-tracking?","-tracking?",-1106885352,null);rxc=new $APP.J(null,"compiler","compiler",-267926731);sxc=new $APP.r(null,"with-let-values","with-let-values",1929572375,null);txc=new $APP.r(null,"class2","class2",-1266396392,null);uxc=new $APP.r(null,"class1","class1",-1905977651,null);vxc=new $APP.r(null,"auto-run","auto-run",-696035332,null);wxc=new $APP.r("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);
Ivc=new $APP.J(null,"auto-run","auto-run",1958400437);lwc=new $APP.J(null,"reagent-render","reagent-render",-985383853);xxc=new $APP.J(null,"contextTypes","contextTypes",-2023853910);yxc=new $APP.r(null,"create-compiler","create-compiler",1059333141,null);zxc=new $APP.r(null,"reaction","reaction",2131401315,null);Evc=new $APP.J(null,"on-dispose","on-dispose",2105306360);DT=new $APP.r(null,"compiler","compiler",1372604796,null);
Axc=new $APP.r("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);Bxc=new $APP.r("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);$vc=new $APP.J(null,"reagentRender","reagentRender",-358306383);Cxc=new $APP.r(null,"cursor","cursor",-1642498285,null);Dxc=new $APP.r("reagent.core","dispose!","reagent.core/dispose!",239740642,null);Exc=new $APP.J(null,"component-did-update","component-did-update",-1468549173);
awc=new $APP.J(null,"displayName","displayName",-809144601);Fxc=new $APP.J(null,"display-name","display-name",694513143);Gxc=new $APP.r("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);Hxc=new $APP.r(null,"destroy","destroy",796871122,null);Ixc=new $APP.r("reagent.core","create-class","reagent.core/create-class",-1100017147,null);Jxc=new $APP.r(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);
Kxc=new $APP.r("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);Lxc=new $APP.r(null,"reagent.debug","reagent.debug",1010511129,null);Mxc=new $APP.r(null,"track!","track!",-516308489,null);Nxc=new $APP.r(null,".error",".error",1756007195,null);Oxc=new $APP.r(null,"as-element","as-element",-2139409597,null);Pxc=new $APP.r("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);
Qxc=new $APP.r("reagent.core","create-element","reagent.core/create-element",-1888667366,null);Rxc=new $APP.r(null,"on-dispose","on-dispose",-549129409,null);ET=new $APP.r(null,"reagent.ratom","reagent.ratom",-2036346616,null);Sxc=new $APP.J(null,"component-will-unmount","component-will-unmount",-2058314698);Txc=new $APP.r(null,"-ratom-context","-ratom-context",1646839514,null);
Uxc=new $APP.r("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);Vxc=new $APP.r("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);Wxc=new $APP.r(null,"class-names","class-names",-1397320704,null);Xxc=new $APP.r(null,"reagent.dom","reagent.dom",-2138920962,null);Yxc=new $APP.r("reagent.core","track","reagent.core/track",1263921785,null);
Zxc=new $APP.r(null,"create-element","create-element",1833774591,null);$xc=new $APP.r(null,"on-set","on-set",1499578057,null);ayc=new $APP.r("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);byc=new $APP.r("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);cyc=new $APP.r(null,"create-class","create-class",-665911586,null);dyc=new $APP.J(null,"childContextTypes","childContextTypes",578717991);
eyc=new $APP.r("reagent.core","atom","reagent.core/atom",1748890217,null);fyc=new $APP.r("reagent.core","cursor","reagent.core/cursor",-1137097804,null);gyc=new $APP.r(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);hyc=new $APP.r("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);iyc=new $APP.r(null,"callback-or-compiler","callback-or-compiler",90200066,null);jyc=new $APP.r(null,"-destroy","-destroy",-557272508,null);
kyc=new $APP.r(null,"track-console","track-console",17070495,null);$APP.FT=new $APP.r(null,"props","props",2093813254,null);lyc=new $APP.J(null,"on-set","on-set",-140953470);rwc=new $APP.J(null,"on-write","on-write",31519475);myc=new $APP.r(null,"reactive?","reactive?",1213887990,null);nyc=new $APP.r("reagent.dom","render","reagent.dom/render",-1216356973,null);oyc=new $APP.r(null,"-destroy!","-destroy!",143253949,null);
pyc=new $APP.r("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);qyc=new $APP.r(null,"make-reaction","make-reaction",1935680112,null);ryc=new $APP.J(null,"contextType","contextType",1033066077);syc=new $APP.r("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);GT=new $APP.r(null,"reagent.core","reagent.core",1841519592,null);
tyc=new $APP.r("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);uyc=new $APP.r(null,"others","others",-569561186,null);vyc=new $APP.J(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);Vwc=new $APP.J(null,"parse-tag","parse-tag",1427313738);wyc=new $APP.J(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);xyc=new $APP.r("reagent.core","track!","reagent.core/track!",-954652078,null);
yyc=new $APP.r("reagent.core","as-element","reagent.core/as-element",-1369748434,null);zyc=new $APP.r(null,"-ratom-generation","-ratom-generation",-176468250,null);Ayc=new $APP.r(null,"adapt-react-class","adapt-react-class",1221068673,null);Byc=new $APP.r("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);Cyc=new $APP.r(null,"reactify-component","reactify-component",-882526483,null);Dyc=new $APP.r("js","console","js/console",-1426368245,null);
Eyc=new $APP.r(null,"destroy__78041__auto__","destroy__78041__auto__",-611971769,null);HT=new $APP.r(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);Fyc=new $APP.r("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);Gyc=new $APP.J(null,"no-cache","no-cache",1588056370);Hyc=new $APP.r("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);Uwc=new $APP.J(null,"function-components","function-components",1492814963);
Iyc=new $APP.r("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);Jyc=new $APP.r(null,"make-track","make-track",-1388299455,null);Kyc=new $APP.r("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);Lyc=new $APP.r("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);bwc=new $APP.J(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);Myc=new $APP.r("reagent.core","class-names","reagent.core/class-names",-1902681251,null);
hwc=new $APP.J(null,"getInitialState","getInitialState",1541760916);Nyc=new $APP.J(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);var Xwc=$APP.iq(2,{});var Oyc=$APP.Zg.o(null),Pyc=function(){var a={};a.warn=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.rc(f,0,null)}return c.call(this,e)}function c(d){return $APP.$g.B(Oyc,$APP.pi,new $APP.N(null,1,5,$APP.O,[$APP.Ov],null),$APP.Xd,$APP.z([$APP.Ge.j($APP.p,d)]))}b.K=0;b.P=function(d){d=$APP.t(d);return c(d)};b.B=c;return b}();a.error=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.rc(f,0,null)}return c.call(this,e)}function c(d){return $APP.$g.B(Oyc,$APP.pi,new $APP.N(null,1,5,$APP.O,[$APP.Hv],null),$APP.Xd,$APP.z([$APP.Ge.j($APP.p,d)]))}b.K=0;b.P=function(d){d=$APP.t(d);return c(d)};b.B=c;return b}();return a}();var Qyc=typeof window!=="undefined"&&window.document!=null,ivc=new $APP.ng(null,new $APP.h(null,2,["aria",null,"data",null],null),null),CT=function CT(a){switch(arguments.length){case 0:return CT.M();case 1:return CT.o(arguments[0]);case 2:return CT.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=2<c.length?new $APP.rc(c.slice(2),0,null):null;return CT.B(arguments[0],arguments[1],c)}};CT.M=function(){return null};
CT.o=function(a){return $APP.bd(a)?(a=$APP.Kk.j(function(b){return $APP.n(b)?pT(b)?$APP.tg(b):b:null},a),$APP.t(a)?$APP.Mk.j(" ",a):null):pT(a)?$APP.tg(a):a};CT.j=function(a,b){return $APP.n(a)?$APP.n(b)?[$APP.p.o(CT.o(a))," ",$APP.p.o(CT.o(b))].join(""):CT.o(a):CT.o(b)};CT.B=function(a,b,c){return $APP.Dd.A(CT,CT.j(a,b),c)};CT.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.B(b,a,c)};CT.K=2;var yT=!1;$APP.AT=$APP.iq(3,{});var gwc=0,Ryc=Qyc?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.n(b))return b;b=a.webkitRequestAnimationFrame;if($APP.n(b))return b;b=a.mozRequestAnimationFrame;if($APP.n(b))return b;b=a.msRequestAnimationFrame;return $APP.n(b)?b:nvc}().bind(a)}():nvc;$APP.g=svc.prototype;$APP.g.flush_after_render=function(){var a=this.Xm;if(a==null)return null;this.Xm=null;return qvc(a)};$APP.g.queue_render=function(a){this.rn==null&&(this.rn=[]);return rvc(this,this.rn,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.jo)return null;this.jo=!0;return Ryc.o?Ryc.o(a):Ryc.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.$m;if(a==null)return null;this.$m=null;return qvc(a)};$APP.g.flush_queues=function(){this.flush_before_flush();pvc();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.jo=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){this.$m==null&&(this.$m=[]);return rvc(this,this.$m,a)};$APP.g.add_after_render=function(a){this.Xm==null&&(this.Xm=[]);return rvc(this,this.Xm,a)};$APP.g.flush_render=function(){var a=this.rn;if(a==null)return null;this.rn=null;a:{a.sort(ovc);for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.cljsIsDirty===!0&&d.forceUpdate();c+=1}else{a=null;break a}a=void 0}return a};$APP.qT=new svc;var sT;$APP.Zg.o(0);var Pvc=null;$APP.g=$APP.Dvc.prototype;$APP.g.eo=$APP.lc;$APP.g.la=function(a,b,c){return Cvc(b,c,"RAtom",new $APP.h(null,1,[$APP.X,this.Oa(null)],null))};$APP.g.ja=function(){return this.meta};$APP.g.na=function(){return $APP.ja(this)};$APP.g.ga=function(a,b){return this===b};$APP.g.le=function(a,b){a=this.state;this.state=b;this.watches!=null&&tT(this,a,b);return b};$APP.g.Wk=function(a,b){return this.le(null,b.o?b.o(this.state):b.call(null,this.state))};
$APP.g.Xk=function(a,b,c){return this.le(null,b.j?b.j(this.state,c):b.call(null,this.state,c))};$APP.g.Yk=function(a,b,c,d){return this.le(null,b.A?b.A(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.Zk=function(a,b,c,d,e){return this.le(null,$APP.Ge.ba(b,this.state,c,d,e))};$APP.g.oi=function(a,b,c){return tT(this,b,c)};$APP.g.Cj=function(a,b,c){return Avc(this,b,c)};$APP.g.Dj=function(a,b){return Bvc(this,b)};$APP.g.ka=function(a,b){return new $APP.Dvc(this.state,b,this.Ik,this.watches)};
$APP.g.Oa=function(){zvc(this);return this.state};var xT=function xT(a){switch(arguments.length){case 1:return xT.o(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return xT.B(arguments[0],c)}};xT.o=function(a){return new $APP.Dvc(a,null,null,null)};xT.B=function(a,b){var c=$APP.ve(b);b=$APP.E.j(c,$APP.l);c=$APP.E.j(c,$APP.gya);return new $APP.Dvc(a,b,c,null)};
xT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};xT.K=1;$APP.g=$APP.Gvc.prototype;$APP.g.eo=$APP.lc;$APP.g.Oa=function(){var a=this,b=a.Em;return b==null?Fvc(function(){return $APP.Ge.j(a.f,a.args)},a.f,a.args,this,null):$APP.Cb(b)};$APP.g.ga=function(a,b){return b instanceof $APP.Gvc&&$APP.G.j(this.f,b.f)&&$APP.G.j(this.args,b.args)};$APP.g.na=function(){return $APP.nc(new $APP.N(null,2,5,$APP.O,[this.f,this.args],null))};
$APP.g.la=function(a,b,c){return Cvc(b,c,"Track",new $APP.h(null,2,[$APP.X,this.Oa(null),$APP.Nz,this.f],null))};var IT=function IT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return IT.B(arguments[0],c)};IT.B=function(a,b){return Jvc(a,b)};IT.K=1;IT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};$APP.g=$APP.Kvc.prototype;
$APP.g._peek=function(){var a=sT;sT=null;try{return this.Oa(null)}finally{sT=a}};$APP.g._set_state=function(a,b){if(a===b)return null;this.state=b;return this.watches!=null?tT(this,a,b):null};$APP.g.eo=$APP.lc;$APP.g.la=function(a,b,c){return Cvc(b,c,"RCursor",new $APP.h(null,2,[$APP.X,this.Oa(null),$APP.Rl,this.path],null))};$APP.g.na=function(){return $APP.nc(new $APP.N(null,2,5,$APP.O,[this.ad,this.path],null))};
$APP.g.ga=function(a,b){return b instanceof $APP.Kvc&&$APP.G.j(this.path,b.path)&&$APP.G.j(this.ad,b.ad)};$APP.g.le=function(a,b){this._set_state(this.state,b);(this.ad!=null?this.ad.V&32768||$APP.lc===this.ad.Pg||(this.ad.V?0:$APP.ib($APP.Bb,this.ad)):$APP.ib($APP.Bb,this.ad))?$APP.G.j(this.path,$APP.ff)?$APP.Le(this.ad,b):$APP.$g.F(this.ad,$APP.Xk,this.path,b):this.ad.j?this.ad.j(this.path,b):this.ad.call(null,this.path,b);return b};
$APP.g.Wk=function(a,b){a=this.le;var c=this._peek();b=b.o?b.o(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Xk=function(a,b,c){a=this.le;var d=this._peek();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Yk=function(a,b,c,d){a=this.le;var e=this._peek();b=b.A?b.A(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.g.Zk=function(a,b,c,d,e){return this.le(null,$APP.Ge.ba(b,this._peek(),c,d,e))};$APP.g.oi=function(a,b,c){return tT(this,b,c)};
$APP.g.Cj=function(a,b,c){return Avc(this,b,c)};$APP.g.Dj=function(a,b){return Bvc(this,b)};$APP.g.Oa=function(){var a=this,b=this,c=a.state,d=function(){var e=a.Em;return e==null?Fvc((a.ad!=null?a.ad.V&32768||$APP.lc===a.ad.Pg||(a.ad.V?0:$APP.ib($APP.Bb,a.ad)):$APP.ib($APP.Bb,a.ad))?function(){return $APP.jk.j($APP.Cb(a.ad),a.path)}:function(){return a.ad.o?a.ad.o(a.path):a.ad.call(null,a.path)},a.ad,a.path,b,null):$APP.Cb(e)}();b._set_state(c,d);return d};$APP.g=$APP.Ovc.prototype;
$APP.g._peek_at=function(){var a=sT;sT=null;try{return this.Oa(null)}finally{sT=a}};$APP.g._handle_change=function(a,b,c){return b===c||this.Gj?null:this.Rh==null?(this.Gj=!0,Pvc==null&&(Pvc=[],$APP.qT.jo===!1&&$APP.qT.schedule()),Pvc.push(this)):this.Rh===!0?this._run(!1):this.Rh.o?this.Rh.o(this):this.Rh.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.rg(a),c=$APP.rg(this.Kk);this.Kk=a;a=$APP.t($APP.dq.j(b,c));for(var d=null,e=0,f=0;;)if(f<e){var k=d.ma(null,f);$APP.Oba(k,this,Nvc);f+=1}else if(a=$APP.t(a))d=a,$APP.jd(d)?(a=$APP.dc(d),f=$APP.ec(d),d=a,e=$APP.B(a),a=f):(a=$APP.w(d),$APP.Oba(a,this,Nvc),a=$APP.x(d),d=null,e=0),f=0;else break;b=$APP.t($APP.dq.j(c,b));c=null;for(e=d=0;;)if(e<d)a=c.ma(null,e),$APP.Wb(a,this),e+=1;else if(b=$APP.t(b))c=b,$APP.jd(c)?(b=$APP.dc(c),d=$APP.ec(c),c=b,a=$APP.B(b),
b=d,d=a):(a=$APP.w(c),$APP.Wb(a,this),b=$APP.x(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.Gj&&this.Kk!=null?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.cp=null,yvc(a,this)}catch(b){return this.cp=this.state=a=b,this.Gj=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.n(a)?this._try_capture(this.f):yvc(this.f,this);this.ev||(this.state=a,this.watches==null||$APP.G.j(b,a)||tT(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.ve(a);a=$APP.E.j(b,Ivc);var c=$APP.E.j(b,lyc),d=$APP.E.j(b,Evc);b=$APP.E.j(b,Gyc);a!=null&&(this.Rh=a);c!=null&&(this.DA=c);d!=null&&(this.jv=d);return b!=null?this.ev=b:null};$APP.g.eo=$APP.lc;$APP.g.la=function(a,b,c){return Cvc(b,c,"Reaction",new $APP.h(null,1,[$APP.X,this.Oa(null)],null))};$APP.g.na=function(){return $APP.ja(this)};$APP.g.ga=function(a,b){return this===b};
$APP.g.Mq=function(){var a=this.state,b=this.Kk;this.Rh=this.state=this.Kk=null;this.Gj=!0;b=$APP.t($APP.rg(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.ma(null,e);$APP.Wb(f,this);e+=1}else if(b=$APP.t(b))c=b,$APP.jd(c)?(b=$APP.dc(c),e=$APP.ec(c),c=b,d=$APP.B(b),b=e):(b=$APP.w(c),$APP.Wb(b,this),b=$APP.x(c),c=null,d=0),e=0;else break;this.jv!=null&&this.jv(a);a=this.kv;if(a==null)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.o?d.o(this):d.call(null,this),c+=1;else return null};$APP.g.Lq=$APP.ba(14);
$APP.g.le=function(a,b){a=this.state;this.state=b;this.DA(a,b);tT(this,a,b);return b};$APP.g.Wk=function(a,b){a=this.le;var c=this._peek_at();b=b.o?b.o(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Xk=function(a,b,c){a=this.le;var d=this._peek_at();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Yk=function(a,b,c,d){a=this.le;var e=this._peek_at();b=b.A?b.A(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.Zk=function(a,b,c,d,e){return this.le(null,$APP.Ge.ba(b,this._peek_at(),c,d,e))};$APP.g.oi=function(a,b,c){return tT(this,b,c)};$APP.g.Cj=function(a,b,c){return Avc(this,b,c)};$APP.g.Dj=function(a,b){a=$APP.ad(this.watches);Bvc(this,b);return!a&&$APP.ad(this.watches)&&this.Rh==null?this.Mq(null):null};
$APP.g.Oa=function(){var a=this.cp;if(a!=null)throw a;(a=sT==null)&&(Qvc.M?Qvc.M():Qvc.call(null));a&&this.Rh==null?this.Gj&&(a=this.state,this.state=this.f.M?this.f.M():this.f.call(null),this.watches==null||$APP.G.j(a,this.state)||tT(this,a,this.state)):(zvc(this),this.Gj&&this._run(!1));return this.state};pvc=Qvc;$APP.uT=function uT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return uT.B(arguments[0],c)};
$APP.uT.B=function(a,b){var c=$APP.ve(b);b=$APP.E.j(c,Ivc);var d=$APP.E.j(c,lyc);c=$APP.E.j(c,Evc);a=new $APP.Ovc(a,null,!0,!1,null,null,null,null);a._set_opts(new $APP.h(null,3,[Ivc,b,lyc,d,Evc,c],null));return a};$APP.uT.K=1;$APP.uT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};var Svc=$APP.uT(null);var zT,Rvc=new $APP.h(null,1,[Gyc,!0],null),ewc=new $APP.h(null,2,[wyc,null,pxc,null],null),Yvc=function(a){var b=$APP.Zg.o($APP.M);return function(c){var d=$APP.E.j($APP.Cb(b),c);if(d!=null)return d;d=a.o?a.o(c):a.call(null,c);$APP.$g.F(b,$APP.lg,c,d);return d}}(function(a){if(typeof a==="string")return a;a=$APP.tg(a);a=$APP.Sh(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Xh.j(a,/-/);var b=$APP.t(a);a=$APP.w(b);b=$APP.x(b);return $APP.Ge.A($APP.p,a,$APP.Mg.j(hvc,b))}),iwc=new $APP.N(null,5,5,$APP.O,
[dyc,xxc,ryc,vyc,Nyc],null);var swc=new $APP.ng(null,new $APP.h(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),twc=!1,Pwc=new $APP.h(null,4,[Fxc,"ReagentInput",Exc,uwc,Sxc,function(a){return a.Fp=null},lwc,function(a,b,c,d,e){xwc(c);return wvc(e,a,b,c,d)}],null);var Mwc=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,Awc={"class":"className","for":"htmlFor",charset:"charSet"},Dwc={},Lwc={};$APP.g=Twc.prototype;$APP.g.ka=function(a,b){return new Twc(this.zf,this.id,this.Fu,this.Yn,b)};$APP.g.ja=function(){return this.tA};$APP.g.RA=function(){return this.id};$APP.g.Rv=function(a,b,c){return this.Yn.A?this.Yn.A(this,b,c):this.Yn.call(null,this,b,c)};
$APP.g.Pv=function(a,b){return"object"!==$APP.ha(b)?b:$APP.id(b)?Swc(b,this,this.Fu):$APP.od(b)?Rwc(b,this):pT(b)?$APP.tg(b):(b!=null?b.V&2147483648||$APP.lc===b.gb||(b.V?0:$APP.ib($APP.Ub,b)):$APP.ib($APP.Ub,b))?$APP.Yg.B($APP.z([b])):b};$APP.g.Qv=function(a,b,c,d,e){return Gwc(this,b,c,d,e)};var Syc=Wwc($APP.M);var Ywc=$APP.Zg.o($APP.M),JT=function JT(a){switch(arguments.length){case 2:return JT.j(arguments[0],arguments[1]);case 3:return JT.A(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};JT.j=function(a,b){return JT.A(a,b,Syc)};
JT.A=function(a,b,c){Qvc();c=$APP.gd(c)?new $APP.N(null,2,5,$APP.O,[rxc.o(c),$APP.JMa.o(c)],null):$APP.Wc(c)?new $APP.N(null,2,5,$APP.O,[Syc,c],null):new $APP.N(null,2,5,$APP.O,[c,null],null);var d=$APP.F.A(c,0,null);c=$APP.F.A(c,1,null);return Zwc(function(){return rT(d,$APP.Wc(a)?a.M?a.M():a.call(null):a)},b,c)};JT.K=3;var KT=function KT(a){switch(arguments.length){case 1:return KT.o(arguments[0]);case 2:return KT.j(arguments[0],arguments[1]);case 3:return KT.A(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return KT.B(arguments[0],arguments[1],arguments[2],c)}};KT.o=function(a){return KT.j(a,null)};KT.j=function(a,b){return $APP.AT.createElement(a,b)};
KT.A=function(a,b,c){return $APP.AT.createElement(a,b,c)};KT.B=function(a,b,c,d){return $APP.Ge.ba($APP.AT.createElement,a,b,c,d)};KT.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};KT.K=3;var LT=function LT(a){switch(arguments.length){case 1:return LT.o(arguments[0]);case 2:return LT.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};LT.o=function(a){return rT(Syc,a)};
LT.j=function(a,b){return rT(b,a)};LT.K=2;var MT=function MT(a){switch(arguments.length){case 1:return MT.o(arguments[0]);case 2:return MT.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};MT.o=function(a){return MT.j(a,Syc)};MT.j=function(a,b){return Vvc(a)?a:mwc(a,b)};MT.K=2;
var NT=function NT(a){switch(arguments.length){case 1:return NT.o(arguments[0]);case 2:return NT.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.p.o(arguments.length)].join(""));}};NT.o=function(a){return jwc(a,Syc)};NT.j=function(a,b){return jwc(a,b)};NT.K=2;
var OT=function OT(a){switch(arguments.length){case 0:return OT.M();case 1:return OT.o(arguments[0]);case 2:return OT.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=2<c.length?new $APP.rc(c.slice(2),0,null):null;return OT.B(arguments[0],arguments[1],c)}};OT.M=function(){return null};OT.o=function(a){return CT.o(a)};OT.j=function(a,b){return CT.j(a,b)};OT.B=function(a,b,c){return $APP.Ge.F(CT,a,b,c)};
OT.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.B(b,a,c)};OT.K=2;$APP.PT=function PT(a){switch(arguments.length){case 1:return PT.o(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return PT.B(arguments[0],c)}};$APP.PT.o=function(a){return xT.o(a)};$APP.PT.B=function(a,b){return $APP.Ge.A(xT,a,b)};
$APP.PT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};$APP.PT.K=1;var QT=function QT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return QT.B(arguments[0],c)};QT.B=function(a,b){return Hvc(a,b)};QT.K=1;QT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};
var RT=function RT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=1<c.length?new $APP.rc(c.slice(1),0,null):null;return RT.B(arguments[0],c)};RT.B=function(a,b){return Jvc(a,b)};RT.K=1;RT.P=function(a){var b=$APP.w(a);a=$APP.x(a);return this.B(b,a)};var ST=function ST(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=3<c.length?new $APP.rc(c.slice(3),0,null):null;return ST.B(arguments[0],arguments[1],arguments[2],c)};
ST.B=function(a,b,c,d){var e=$APP.sj.o("with-let");a=$APP.Ng.o(e);var f=$APP.sj.o("init");c=$APP.Mf.j(new $APP.N(null,2,5,$APP.O,[f,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.GTa,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.TSa,null,1,null),new $APP.I(null,e,null,1,null)))),null,1,null))))],null),$APP.$m.j(function(q,u){if($APP.Ee(q))return u;q=$APP.Od(q,2);return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Ch,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,
$APP.tSa,null,1,null),new $APP.I(null,f,null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.rz,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,Jxc,null,1,null),new $APP.I(null,e,null,1,null),$APP.z([new $APP.I(null,q,null,1,null)])))),null,1,null)))),null,1,null)])))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.LGa,null,1,null),new $APP.I(null,e,null,1,null),$APP.z([new $APP.I(null,q,null,1,null),new $APP.I(null,
u,null,1,null)])))),null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.tBa,null,1,null),new $APP.I(null,e,null,1,null),$APP.z([new $APP.I(null,q,null,1,null)])))),null,1,null)]))))},c));var k=function(){var q=$APP.Tc(d);return $APP.od(q)&&$APP.G.j($APP.yh,$APP.w(q))?new $APP.N(null,2,5,$APP.O,[$APP.sg(d),$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.M()))),null,1,null),$APP.z([$APP.wc(q)]))))],null):new $APP.N(null,
2,5,$APP.O,[d,null],null)}();b=$APP.F.A(k,0,null);k=$APP.F.A(k,1,null);k=$APP.n(k)?new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,Eyc,null,1,null),new $APP.I(null,k,null,1,null))))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Ch,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.o(new $APP.I(null,Iyc,null,1,null)))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,
$APP.Hs,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.iu,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,ayc,null,1,null),new $APP.I(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,Axc,null,1,null),new $APP.I(null,e,null,1,null),$APP.z([new $APP.I(null,Eyc,null,1,null)])))),null,1,null)])))),null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.o(new $APP.I(null,Eyc,null,1,null)))),
null,1,null)])))),null,1,null)])))),null,1,null):null;var m=$APP.sj.o("res");return $APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.j(new $APP.I(null,e,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,Lyc,null,1,null),new $APP.I(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.z([new $APP.I(null,null,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.bl,null,1,null),new $APP.I(null,
$APP.Mf.j(c,new $APP.N(null,2,5,$APP.O,[m,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.Bh,null,1,null),b)))],null)),null,1,null),$APP.z([k,new $APP.I(null,m,null,1,null)])))),null,1,null)]))))};ST.K=3;ST.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);var d=$APP.x(c);c=$APP.w(d);d=$APP.x(d);return this.B(b,a,c,d)};var TT=function TT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=0<c.length?new $APP.rc(c.slice(0),0,null):null;return TT.B(c)};
TT.B=function(a){return $APP.al.o($APP.t($APP.R.j(new $APP.I(null,nxc,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.zy,null,1,null),new $APP.I(null,$APP.Fd($APP.al.o($APP.t($APP.R.M()))),null,1,null),$APP.z([a])))),null,1,null))))};TT.K=0;TT.P=function(a){return this.B($APP.t(a))};
var UT=$APP.Wm(GT),Tyc=$APP.$f([cyc,$APP.ASa,$APP.ALa,$APP.eza,Wxc,zxc,Oxc,Cyc,Zxc,oxc,Cxc,Mxc,yxc,Ayc],[function(){var a=new $APP.qc(function(){return NT},Ixc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,cyc,"reagent/core.cljs",19,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.tw],null),new $APP.N(null,2,5,$APP.O,[$APP.tw,DT],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,
$APP.O,[$APP.tw],null),new $APP.N(null,2,5,$APP.O,[$APP.tw,DT],null)),$APP.Ox,$APP.Q(null,null)],null),1,68,68,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.tw],null),new $APP.N(null,2,5,$APP.O,[$APP.tw,DT],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.n(NT)?NT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return QT},Yxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,$APP.ASa,"reagent/core.cljs",
12,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Qu,$APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,218,218,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.n(QT)?QT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return ST},Vxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Gk,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,$APP.ALa,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,$APP.Q($APP.Q($APP.ww,$APP.Qw)),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.ww,$APP.vh,$APP.Qw],null)),$APP.Ox,$APP.Q(null)],null),1,10,!0,10,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.ww,$APP.vh,$APP.Qw],null)),null,$APP.n(ST)?ST.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=
$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return $APP.PT},eyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,$APP.eza,"reagent/core.cljs",11,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,1,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.mv],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null),new $APP.N(null,3,5,$APP.O,[$APP.mv,
$APP.vh,$APP.wAa],null)),$APP.Ox,$APP.Q(null,null)],null),1,211,211,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null),new $APP.N(null,3,5,$APP.O,[$APP.mv,$APP.vh,$APP.wAa],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.n($APP.PT)?$APP.PT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],
null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return OT},Myc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Wxc,"reagent/core.cljs",18,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,3,5,$APP.O,[$APP.ff,new $APP.N(null,1,5,$APP.O,[$APP.LCa],null),new $APP.N(null,2,5,$APP.O,
[uxc,txc],null)],null),$APP.U,$APP.Q($APP.ff,new $APP.N(null,1,5,$APP.O,[$APP.LCa],null),new $APP.N(null,2,5,$APP.O,[uxc,txc],null),new $APP.N(null,4,5,$APP.O,[uxc,txc,$APP.vh,uyc],null)),$APP.Ox,$APP.Q(null,null,null,null)],null),1,179,179,$APP.Q($APP.ff,new $APP.N(null,1,5,$APP.O,[$APP.LCa],null),new $APP.N(null,2,5,$APP.O,[uxc,txc],null),new $APP.N(null,4,5,$APP.O,[uxc,txc,$APP.vh,uyc],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.n(OT)?OT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return TT},tyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Gk,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,zxc,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,-2,$APP.Wv,-2,$APP.mz,$APP.Q($APP.vc),$APP.U,$APP.Q($APP.ff),$APP.Ox,$APP.Q(null)],null),1,62,!0,62,$APP.Q($APP.ff),null,$APP.n(TT)?TT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=
new $APP.qc(function(){return LT},yyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Oxc,"reagent/core.cljs",17,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.Du],null),new $APP.N(null,2,5,$APP.O,[$APP.Du,DT],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Du],null),new $APP.N(null,2,5,$APP.O,[$APP.Du,DT],null)),$APP.Ox,$APP.Q(null,null)],null),1,46,46,$APP.Q(new $APP.N(null,
1,5,$APP.O,[$APP.Du],null),new $APP.N(null,2,5,$APP.O,[$APP.Du,DT],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.n(LT)?LT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),
function(){var a=new $APP.qc(function(){return MT},pyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Cyc,"reagent/core.cljs",25,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,2,$APP.Wv,2,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.Pu],null),new $APP.N(null,2,5,$APP.O,[$APP.Pu,DT],null)],null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null),new $APP.N(null,2,5,$APP.O,[$APP.Pu,DT],null)),$APP.Ox,$APP.Q(null,null)],null),1,
59,59,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null),new $APP.N(null,2,5,$APP.O,[$APP.Pu,DT],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.n(MT)?MT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=
$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return KT},Qxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Zxc,"reagent/core.cljs",21,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,3,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.Et],null),new $APP.N(null,2,5,$APP.O,[$APP.Et,$APP.FT],null),new $APP.N(null,3,5,$APP.O,[$APP.Et,$APP.FT,$APP.Py],null)],
null),$APP.U,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Et],null),new $APP.N(null,2,5,$APP.O,[$APP.Et,$APP.FT],null),new $APP.N(null,3,5,$APP.O,[$APP.Et,$APP.FT,$APP.Py],null),new $APP.N(null,5,5,$APP.O,[$APP.Et,$APP.FT,$APP.Py,$APP.vh,$APP.gu],null)),$APP.Ox,$APP.Q(null,null,null,null)],null),1,17,17,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Et],null),new $APP.N(null,2,5,$APP.O,[$APP.Et,$APP.FT],null),new $APP.N(null,3,5,$APP.O,[$APP.Et,$APP.FT,$APP.Py],null),new $APP.N(null,5,5,$APP.O,[$APP.Et,$APP.FT,
$APP.Py,$APP.vh,$APP.gu],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',$APP.n(KT)?KT.pa:null])),
b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return axc},Dxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,oxc,"reagent/core.cljs",15,1,242,242,$APP.Q(new $APP.N(null,
1,5,$APP.O,[$APP.mv],null)),"Stop the result of track! from updating.",$APP.n(axc)?axc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return bxc},fyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,
$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Cxc,"reagent/core.cljs",13,1,272,272,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.ny,$APP.wz],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.n(bxc)?bxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return RT},xyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Mxc,"reagent/core.cljs",
13,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Qu,$APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,234,234,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.n(RT)?RT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?
null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return cxc},byc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,yxc,"reagent/core.cljs",22,1,353,353,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.dy],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.n(cxc)?cxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return $wc},mxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[GT,Ayc,"reagent/core.cljs",24,1,52,
52,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.Pu],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.n($wc)?$wc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,
b,d)}()]),VT=$APP.Wm(ET),Uyc=$APP.$f([sxc,$APP.eza,Jyc,jyc,gyc,myc,oyc,qyc,Txc,kxc,Mxc,zyc],[function(){var a=new $APP.qc(function(){return Mvc},Lyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[ET,sxc,"reagent/ratom.cljs",22,1,329,329,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.ou],null)),null,$APP.n(Mvc)?Mvc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],
null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return xT},Kyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[ET,$APP.eza,"reagent/ratom.cljs",11,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,1,5,$APP.O,[new $APP.N(null,1,5,$APP.O,[$APP.mv],null)],null),$APP.U,$APP.Q(new $APP.N(null,
1,5,$APP.O,[$APP.mv],null),new $APP.N(null,3,5,$APP.O,[$APP.mv,$APP.vh,new $APP.h(null,1,[$APP.et,new $APP.N(null,2,5,$APP.O,[$APP.Rs,$APP.wHa],null)],null)],null)),$APP.Ox,$APP.Q(null,null)],null),1,172,172,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.mv],null),new $APP.N(null,3,5,$APP.O,[$APP.mv,$APP.vh,new $APP.h(null,1,[$APP.et,new $APP.N(null,2,5,$APP.O,[$APP.Rs,$APP.wHa],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.n(xT)?xT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);
a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return Hvc},Byc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[ET,Jyc,"reagent/ratom.cljs",17,1,228,228,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Qu,$APP.st],
null)),null,$APP.n(Hvc)?Hvc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return ixc},wxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,jyc,"sci/configs/reagent/reagent.cljs",
15,1,106,106,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.C($APP.jv,new $APP.h(null,1,[$APP.bi,$APP.cx],null))],null)),null,$APP.n(ixc)?ixc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return gxc},Uxc,$APP.$f([$APP.Ck,
$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,gyc,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.C($APP.jv,new $APP.h(null,1,[$APP.bi,$APP.cx],null)),$APP.C($APP.Pu,new $APP.h(null,1,[$APP.bi,$APP.cx],null))],null)),null,$APP.n(gxc)?gxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,
b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return xvc},Iyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.bi,$APP.U,$APP.S,$APP.Nh],[ET,myc,"reagent/ratom.cljs",25,1,17,17,$APP.wu,$APP.Q($APP.ff),null,xvc?xvc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?
$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return hxc},Fyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,oyc,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.C($APP.jv,new $APP.h(null,1,[$APP.bi,$APP.cx],null)),Hxc],null)),null,$APP.n(hxc)?hxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:
$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return $APP.uT},nxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[ET,qyc,"reagent/ratom.cljs",20,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,
1,5,$APP.O,[$APP.Q($APP.Qu,new $APP.h(null,1,[$APP.et,new $APP.N(null,3,5,$APP.O,[vxc,$xc,Rxc],null)],null))],null),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,new $APP.h(null,1,[$APP.et,new $APP.N(null,3,5,$APP.O,[vxc,$xc,Rxc],null)],null)],null)),$APP.Ox,$APP.Q(null)],null),1,517,517,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,new $APP.h(null,1,[$APP.et,new $APP.N(null,3,5,$APP.O,[vxc,$xc,Rxc],null)],null)],null)),null,$APP.n($APP.uT)?$APP.uT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);
a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return dxc},hyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,Txc,"sci/configs/reagent/reagent.cljs",21,1,85,85,$APP.Q($APP.ff),"Read-only access to the ratom context.",
$APP.n(dxc)?dxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return exc},syc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,kxc,"sci/configs/reagent/reagent.cljs",
18,1,90,90,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.C($APP.mv,new $APP.h(null,1,[$APP.bi,$APP.cx],null))],null)),null,$APP.n(exc)?exc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return IT},lxc,$APP.$f([$APP.Ck,
$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[ET,Mxc,"reagent/ratom.cljs",13,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,1,$APP.Wv,1,$APP.mz,new $APP.N(null,1,5,$APP.O,[$APP.Q($APP.Qu,$APP.st)],null),$APP.U,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),$APP.Ox,$APP.Q(null)],null),1,242,242,$APP.Q(new $APP.N(null,3,5,$APP.O,[$APP.Qu,$APP.vh,$APP.st],null)),null,$APP.n(IT)?IT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,
4,[$APP.Ck,UT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),function(){var a=new $APP.qc(function(){return fxc},Gxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,zyc,"sci/configs/reagent/reagent.cljs",24,1,94,94,$APP.Q(new $APP.N(null,1,5,$APP.O,[$APP.C($APP.mv,new $APP.h(null,1,[$APP.bi,$APP.cx],null))],
null)),null,$APP.n(fxc)?fxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,VT,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}()]),Vyc=$APP.Wm(Lxc),WT=function WT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;c=2<c.length?new $APP.rc(c.slice(2),0,null):null;
return WT.B(arguments[0],arguments[1],c)};
WT.B=function(a,b,c){return $APP.n(!0)?$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Hs,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.YOa,null,1,null),new $APP.I(null,Dyc,null,1,null)))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,Nxc,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.B(new $APP.I(null,$APP.Ch,null,1,null),new $APP.I(null,$APP.al.o($APP.t($APP.R.o(new $APP.I(null,Hyc,null,1,null)))),null,1,null),$APP.z([new $APP.I(null,
Pxc,null,1,null),new $APP.I(null,Dyc,null,1,null)])))),null,1,null),$APP.z([new $APP.I(null,$APP.al.o($APP.t($APP.R.j(new $APP.I(null,$APP.$t,null,1,null),c))),null,1,null)])))),null,1,null)])))):null};WT.K=2;WT.P=function(a){var b=$APP.w(a),c=$APP.x(a);a=$APP.w(c);c=$APP.x(c);return this.B(b,a,c)};
var Wyc=new $APP.h(null,3,[$APP.sFa,function(){var a=new $APP.qc(function(){return WT},Bxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Gk,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,$APP.sFa,"sci/configs/reagent/reagent.cljs",20,new $APP.h(null,6,[$APP.Us,!0,$APP.mm,0,$APP.Wv,0,$APP.mz,$APP.Q($APP.Q($APP.Yx)),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.Yx],null)),$APP.Ox,$APP.Q(null)],null),1,132,!0,132,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.vh,$APP.Yx],null)),"Print with console.error.",
$APP.n(WT)?WT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Vyc,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),qxc,function(){var a=new $APP.qc(function(){return jxc},Kxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[HT,qxc,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.Q($APP.ff),null,$APP.n(jxc)?jxc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Vyc,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}(),kyc,function(){var a=new $APP.qc(function(){return Pyc},Pxc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],
[Lxc,kyc,"reagent/debug.cljs",23,1,10,10,$APP.vc,null,$APP.n(Pyc)?Pyc.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Vyc,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}()],null);var Xyc=$APP.Wm(Xxc),Yyc=new $APP.h(null,1,[$APP.Mv,function(){var a=new $APP.qc(function(){return JT},nyc,$APP.$f([$APP.Ck,$APP.T,$APP.wi,$APP.Wp,$APP.Xy,$APP.Ui,$APP.xi,$APP.Xp,$APP.U,$APP.S,$APP.Nh],[Xxc,$APP.Mv,"reagent/dom.cljs",13,new $APP.h(null,6,[$APP.Us,!1,$APP.mm,3,$APP.Wv,3,$APP.mz,new $APP.N(null,2,5,$APP.O,[new $APP.N(null,2,5,$APP.O,[$APP.Ix,$APP.Cya],null),new $APP.N(null,3,5,$APP.O,[$APP.Ix,$APP.Cya,iyc],null)],null),$APP.U,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Ix,$APP.Cya],null),
new $APP.N(null,3,5,$APP.O,[$APP.Ix,$APP.Cya,iyc],null)),$APP.Ox,$APP.Q(null,null)],null),1,28,28,$APP.Q(new $APP.N(null,2,5,$APP.O,[$APP.Ix,$APP.Cya],null),new $APP.N(null,3,5,$APP.O,[$APP.Ix,$APP.Cya,iyc],null)),"Render a Reagent component into the DOM. The first argument may be\n  either a vector (using Reagent's Hiccup syntax), or a React element.\n  The second argument should be a DOM node.\n\n  Optionally takes a callback that is called when the component is in place.\n\n  Returns the mounted component instance.",
$APP.n(JT)?JT.pa:null])),b=$APP.Cb(a),c=$APP.Yc(a);a=$APP.n(null)?null:$APP.T.o(c);var d=new $APP.h(null,4,[$APP.Ck,Xyc,$APP.T,a,$APP.U,$APP.U.o(c),$APP.S,$APP.S.o(c)],null);return $APP.n($APP.cl.o(c))?$APP.Tm(a,b,d):$APP.n(function(){var e=$APP.Gk.o(c);return $APP.n(e)?e:$APP.Rk.o(c)}())?$APP.Um(a,b,d):$APP.Sm(a,b,d)}()],null);$APP.bn(new $APP.h(null,1,[$APP.Wk,new $APP.h(null,4,[GT,Tyc,Xxc,Yyc,ET,Uyc,Lxc,Wyc],null)],null));
}).call(this);