bb build.clj

#!/bin/bash
set -e

# Usage: ./build.sh [plugin-name(s)]

if [ "$#" -gt 0 ]; then
	BUILD_DIR="$1"
else
	BUILD_DIR="all"
fi

# if the build failed, shadow-cljs.edn might be left behind, so remove it
# (will be generated by scittle/build)
rm -f "$BUILD_DIR"/shadow-cljs.edn

bb build.clj "$@" && cd "$BUILD_DIR" && bb release && find resources/public

echo "Build complete"
