bb build.clj

#!/bin/bash
set -e

# Usage: ./build.sh [plugin-name]

PLUGIN="$1"
if [ -n "$PLUGIN" ]; then
	BUILD_DIR="$PLUGIN"
	bb build.clj "$PLUGIN"
else
	BUILD_DIR="all"
	bb build.clj
fi

cd "$BUILD_DIR" && bb release && find resources/public

# if the build failed, shadow-cljs.edn might be left behind, so remove it
# shadow-cljs.edn is generated by scittle/build
rm -f "$BUILD_DIR"/shadow-cljs.edn
