bb build.clj

#!/bin/bash
set -e

# Usage: ./build.sh [plugin-name]


if [ "$#" -gt 0 ]; then
	BUILD_DIR="$1"
else
	BUILD_DIR="all"
fi

bb build.clj "$@" && cd "$BUILD_DIR" && bb release && find resources/public

# if the build failed, shadow-cljs.edn might be left behind, so remove it
# shadow-cljs.edn is generated by scittle/build
rm -f "$BUILD_DIR"/shadow-cljs.edn
