#!/bin/bash
set -e

bb build.clj
cd all && bb release && find resources/public

# if the build failed, shadow-cljs.edn might be left behind, so remove it
# shadow-cljs.edn is generated by scittle/build
rm -f all/shadow-cljs.edn
