
name: CI
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Clojure and Babashka
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
          bb: latest

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Build plugins
        run: bb build.clj

      - name: Release build
        run: bb release
        working-directory: all

      - name: Publish to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ./publish-gh-pages.sh
